"""
Redstone lighting systems from the Minecraft Guide to Creative.

Reference knowledge for prompts — redstone circuits are NOT generated by the model.
The lighting_system_house book build captures the structural shell.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class LightingSystem:
  id: str
  name: str
  aliases: tuple[str, ...]
  blocks: tuple[str, ...]
  tip: str


def _b(name: str) -> str:
  if name.startswith("minecraft:"):
    return name
  return f"minecraft:{name}"


LIGHTING_SYSTEMS: tuple[LightingSystem, ...] = (
  LightingSystem(
    id="ceiling_lamps",
    name="hidden ceiling lighting",
    aliases=("ceiling light", "redstone lamp ceiling", "hidden wiring", "lighting system", "double wall"),
    blocks=(_b("redstone_lamp"), _b("redstone_dust"), _b("lever")),
    tip="Double-wall gap hides redstone; lever powers ceiling redstone lamp grid",
  ),
  LightingSystem(
    id="floor_lamps",
    name="floor lighting",
    aliases=("floor light", "underfloor light", "kitchen light", "bathroom light"),
    blocks=(_b("redstone_lamp"), _b("redstone_dust"), _b("repeater")),
    tip="Redstone lamps embedded in wall base, powered from beneath the floor",
  ),
  LightingSystem(
    id="security_light",
    name="security tripwire light",
    aliases=("security light", "tripwire", "entrance light", "motion light"),
    blocks=(_b("redstone_lamp"), _b("tripwire_hook"), _b("oak_fence")),
    tip="Tripwire-activated lamp on fence post at entrance",
  ),
  LightingSystem(
    id="daylight_auto",
    name="automatic daylight lighting",
    aliases=("automatic light", "daylight sensor", "sunset light", "auto light"),
    blocks=(_b("daylight_detector"), _b("redstone_lamp"), _b("redstone_dust")),
    tip="Daylight sensor on roof powers bedroom lamps at sunset automatically",
  ),
)


def detect_lighting_system(prompt: str) -> list[LightingSystem]:
  lower = prompt.lower()
  return [s for s in LIGHTING_SYSTEMS if any(a in lower for a in s.aliases)]


def lighting_keywords(system: LightingSystem) -> list[str]:
  return [system.name] + [b.removeprefix("minecraft:").replace("_", " ") for b in system.blocks[:2]]
