"""
Redstone transport systems from the Minecraft Guide to Creative.

Reference knowledge for prompts — minecart circuits are NOT generated by the model.
Useful for mining scenes, industrial builds, and underground terminals.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class TransportSystem:
  id: str
  name: str
  aliases: tuple[str, ...]
  blocks: tuple[str, ...]
  tip: str


def _b(name: str) -> str:
  if name.startswith("minecraft:"):
    return name
  return f"minecraft:{name}"


TRANSPORT_SYSTEMS: tuple[TransportSystem, ...] = (
  TransportSystem(
    id="vertical_shaft",
    name="vertical item transport",
    aliases=(
      "vertical transport", "item elevator", "minecart elevator", "vertical shaft",
      "item transport", "transport system", "bedrock to surface",
    ),
    blocks=(
      _b("powered_rail"), _b("rail"), _b("hopper"), _b("chest"),
      _b("comparator"), _b("redstone_torch"),
    ),
    tip="5x5 zigzag powered-rail shaft; comparator holds cart until empty at bottom, full at top",
  ),
  TransportSystem(
    id="hopper_loader",
    name="hopper loading station",
    aliases=("hopper loader", "loading station", "hopper minecart", "auto loader"),
    blocks=(_b("hopper"), _b("chest"), _b("powered_rail"), _b("comparator")),
    tip="Chest feeds hopper above rail; comparator detects full minecart before sending it",
  ),
  TransportSystem(
    id="hopper_unloader",
    name="hopper unloading station",
    aliases=("hopper unloader", "unloading station", "auto unloader", "item collector"),
    blocks=(_b("hopper"), _b("chest"), _b("powered_rail"), _b("redstone_torch")),
    tip="Hopper pulls items from cart into chest; torch deactivates rail until cart is empty",
  ),
  TransportSystem(
    id="manual_hopper",
    name="manual hopper collection",
    aliases=("manual hopper", "hopper over rail", "simple collection", "hopper line"),
    blocks=(_b("hopper"), _b("rail"), _b("powered_rail"), _b("chest")),
    tip="Row of hoppers suspended over parallel tracks — no redstone, carts collect drops",
  ),
  TransportSystem(
    id="mining_terminal",
    name="mining terminal",
    aliases=("mining terminal", "mine terminal", "surface terminal", "mine entrance building"),
    blocks=(_b("stone_bricks"), _b("glass_pane"), _b("quartz_block"), _b("powered_rail")),
    tip="Modern glass-and-stone building at surface disguises vertical shaft entrance",
  ),
  TransportSystem(
    id="underground_network",
    name="underground rail network",
    aliases=(
      "underground rail", "mine tracks", "rail junction", "mining network",
      "cargo depot", "underground system",
    ),
    blocks=(_b("rail"), _b("powered_rail"), _b("lever"), _b("chest")),
    tip="Stone-brick tunnels with lever-controlled junctions and chest cargo depots",
  ),
)


def detect_transport_system(prompt: str) -> list[TransportSystem]:
  lower = prompt.lower()
  return [s for s in TRANSPORT_SYSTEMS if any(a in lower for a in s.aliases)]


def transport_keywords(system: TransportSystem) -> list[str]:
  return [system.name] + [b.removeprefix("minecraft:").replace("_", " ") for b in system.blocks[:2]]
