"""Export voxel grids to Litematica .litematic files."""

from __future__ import annotations

from pathlib import Path

import numpy as np

from ..data.palette import BlockPalette


def export_litematic(
  voxel_indices: np.ndarray,
  palette: BlockPalette,
  output_path: Path,
  name: str = "Generated Build",
  author: str = "Minecraft Builder AI",
  description: str = "",
) -> Path:
  """
  Write a (D, H, W) integer array of palette indices to a .litematic file.
  """
  from litemapy import BlockState, Region, Schematic

  d, h, w = voxel_indices.shape
  region = Region(0, 0, 0, d, h, w)

  for x in range(d):
    for y in range(h):
      for z in range(w):
        idx = int(voxel_indices[x, y, z])
        block_id = palette.decode(idx)
        if block_id == "minecraft:air" or idx == 0:
          continue
        region[x, y, z] = _parse_block_state(block_id)

  schem = region.as_schematic(
    name=name,
    author=author,
    description=description or f"Generated by Minecraft Builder AI",
  )
  output_path = Path(output_path)
  output_path.parent.mkdir(parents=True, exist_ok=True)
  schem.save(str(output_path))
  return output_path


def _parse_block_state(block_id: str):
  from litemapy import BlockState

  if "[" in block_id:
    base, props_str = block_id.split("[", 1)
    props_str = props_str.rstrip("]")
    props = {}
    for pair in props_str.split(","):
      if "=" in pair:
        k, v = pair.split("=", 1)
        props[k.strip()] = v.strip()
    return BlockState(base, props=props)
  return BlockState(block_id)
