"""
Bite-Sized Builds catalog — one entry per build from the book photos.

Drop photos in data/book_photos/bite_sized_builds/ (or send in chat).
Each build gets: registry entry, procedural generator, training caption.
"""

from __future__ import annotations

from .registry import BookBuild, BuildZone

BITE_SIZED_BUILDS: dict[str, BookBuild] = {
  "bite_creeper": BookBuild(
    id="bite_creeper",
    name="Creeper in the Woods",
    theme="fantasy",
    biome="forest",
    caption=(
      "a giant creeper statue in the woods, 5-block cube head with gray concrete face, "
      "rectangular body and two separate blocky feet, 16 blocks tall"
    ),
    palette=(
      "minecraft:green_concrete",
      "minecraft:lime_terracotta",
      "minecraft:green_concrete_powder",
      "minecraft:white_concrete",
      "minecraft:gray_concrete",
      "minecraft:green_terracotta",
      "minecraft:grass_block",
      "minecraft:oak_log",
      "minecraft:oak_leaves",
    ),
    zones=(
      BuildZone(
        name="creeper head",
        size=(5, 5, 5),
        materials=("green_concrete", "lime_terracotta", "gray_concrete"),
        features=("5x5 cube head", "gray concrete eyes and mouth"),
        interior=("gray concrete face",),
      ),
      BuildZone(
        name="creeper body",
        size=(5, 7, 3),
        materials=("green_concrete_powder", "white_concrete", "lime_terracotta"),
        features=("5x7x3 rectangular torso", "mixed green texture"),
        interior=(),
      ),
      BuildZone(
        name="creeper feet",
        size=(6, 4, 5),
        materials=("green_terracotta", "green_concrete"),
        features=("two 3x4x5 leg blocks", "gap between feet"),
        interior=(),
      ),
      BuildZone(
        name="forest clearing",
        size=(16, 16, 16),
        materials=("grass_block", "oak_log", "oak_leaves"),
        features=("oak trees", "natural woodland setting"),
        interior=(),
      ),
    ),
    exterior_features=(
      "forest setting with oak trees",
      "16 blocks tall mob statue",
      "gray concrete eyes and mouth on head",
      "green concrete powder and terracotta body texture",
    ),
    tips=(
      "Build from basic rectangular shapes — head, body, two feet",
      "Use temporary blocks to join feet and body, remove when done",
      "Mix green concrete, powder, terracotta and white for texture",
      "Rated 1-star difficulty, ~20 minutes",
    ),
  ),
  "bite_toadstool_house": BookBuild(
    id="bite_toadstool_house",
    name="Toadstool House",
    theme="fantasy",
    biome="forest",
    caption=(
      "a magical toadstool house at the forest edge, cobblestone cottage base with "
      "mushroom stem tower and red mushroom cap bedroom, ladder through the stem"
    ),
    palette=(
      "minecraft:cobblestone",
      "minecraft:mossy_cobblestone",
      "minecraft:spruce_planks",
      "minecraft:mushroom_stem",
      "minecraft:red_mushroom_block",
      "minecraft:oak_stairs",
      "minecraft:oak_slab",
      "minecraft:spruce_stairs",
      "minecraft:glass_pane",
      "minecraft:lantern",
      "minecraft:vine",
      "minecraft:red_bed",
    ),
    zones=(
      BuildZone(
        name="ground floor cottage",
        size=(7, 5, 8),
        materials=("cobblestone", "mossy_cobblestone", "spruce_planks", "mushroom_stem"),
        features=("7x8 foundation", "oak door", "trapdoor ladder cellar"),
        interior=("chests", "ladder to stem"),
      ),
      BuildZone(
        name="stem staircase",
        size=(3, 10, 3),
        materials=("mushroom_stem",),
        features=("3x3 hollow pillar", "ladder shaft", "vines"),
        interior=("ladder"),
      ),
      BuildZone(
        name="mushroom cap bedroom",
        size=(9, 6, 9),
        materials=("red_mushroom_block", "spruce_planks", "spruce_log"),
        features=("round red cap", "four windows", "spruce roof dormers", "hanging lanterns"),
        interior=("red bed", "chests", "crafting table", "green carpet"),
      ),
    ),
    exterior_features=(
      "red and white spotted mushroom cap roof",
      "white mushroom stem tower",
      "mossy cobblestone forest cottage base",
      "spruce fence lanterns under cap",
      "vine decoration on stem",
      "rose bushes and oak fence garden",
    ),
    tips=(
      "Foundation is 7×8 cobblestone outline with spruce plank center path",
      "Stem is 3×3 mushroom stem rings with ladder through center",
      "Cap flares from 5×5 to rounded 9-block ring with zigzag red mushroom blocks",
      "Rated 2-star difficulty, ~35 minutes",
    ),
  ),
  "bite_alarm_system": BookBuild(
    id="bite_alarm_system",
    name="Alarm System",
    theme="industrial",
    biome="plains",
    caption=(
      "a redstone alarm system stone brick doorway, double spruce doors with pressure "
      "plates, glowstone arch facade, bells and observers on the side"
    ),
    palette=(
      "minecraft:stone_bricks",
      "minecraft:chiseled_stone_bricks",
      "minecraft:polished_andesite_stairs",
      "minecraft:stone",
      "minecraft:spruce_door",
      "minecraft:stone_pressure_plate",
      "minecraft:glowstone",
      "minecraft:stone_button",
      "minecraft:bell",
      "minecraft:observer",
      "minecraft:redstone_torch",
      "minecraft:redstone_dust",
    ),
    zones=(
      BuildZone(
        name="security entrance",
        size=(4, 4, 4),
        materials=("stone_bricks", "spruce_door", "stone_pressure_plate"),
        features=("double spruce doors", "pressure plate floor", "4x4 frame"),
        interior=("spruce door", "stone pressure plate", "redstone dust"),
      ),
      BuildZone(
        name="lit archway",
        size=(4, 2, 4),
        materials=("chiseled_stone_bricks", "polished_andesite_stairs", "glowstone"),
        features=("arched roof", "glowstone light", "stone buttons"),
        interior=("glowstone", "stone button"),
      ),
      BuildZone(
        name="bell alarm chamber",
        size=(2, 4, 2),
        materials=("bell", "observer", "redstone_torch", "stone_brick_stairs"),
        features=("bell chain", "observer trigger", "hidden redstone"),
        interior=("bell", "observer", "redstone torch"),
      ),
    ),
    exterior_features=(
      "stone brick wall integration",
      "glowstone archway lighting",
      "pressure plate triggered bells",
      "redstone dust under floor plates",
    ),
    tips=(
      "4×4 stone foundation with U-shaped redstone dust under pressure plates",
      "Pressure plates deactivate redstone torch to ring bells via observers",
      "Easily adaptable — connect to hidden traps for extra security",
      "Rated 2-star difficulty, ~10 minutes",
    ),
  ),
  "bite_combination_lock": BookBuild(
    id="bite_combination_lock",
    name="Combination Lock",
    theme="industrial",
    biome="plains",
    caption=(
      "a redstone combination lock vault door, four levers on stone brick wall with "
      "redstone lamps above, iron door, AND gate torch notches behind the wall"
    ),
    palette=(
      "minecraft:stone_bricks",
      "minecraft:polished_andesite",
      "minecraft:cobblestone_wall",
      "minecraft:chiseled_polished_blackstone",
      "minecraft:stone",
      "minecraft:iron_door",
      "minecraft:lever",
      "minecraft:redstone_lamp",
      "minecraft:redstone_torch",
      "minecraft:redstone_dust",
    ),
    zones=(
      BuildZone(
        name="lever lock panel",
        size=(9, 5, 3),
        materials=("stone_bricks", "polished_andesite", "chiseled_polished_blackstone"),
        features=("four levers", "redstone lamps", "9x5 wall panel"),
        interior=("lever", "redstone lamp"),
      ),
      BuildZone(
        name="hidden AND gate chamber",
        size=(9, 3, 2),
        materials=("redstone_torch", "redstone_dust", "stone"),
        features=("AND gate notches", "torch and stone code slots"),
        interior=("redstone torch", "redstone dust", "stone code block"),
      ),
      BuildZone(
        name="vault iron door",
        size=(2, 3, 1),
        materials=("iron_door", "cobblestone_wall"),
        features=("iron door release", "hidden wiring"),
        interior=("iron door",),
      ),
    ),
    exterior_features=(
      "9-block-wide stone security wall",
      "glowing redstone lamps above each lever",
      "polished andesite and blackstone trim",
      "scalable to 5 or 6 levers for more combinations",
    ),
    tips=(
      "9×5×3 wall panel with levers and lamps on the face",
      "AND gate: redstone torches and stone blocks create code notches behind wall",
      "Move torches and stone beneath to set the combination",
      "Rated 3-star difficulty, ~10 minutes",
    ),
  ),
  "bite_fairy_treehouse": BookBuild(
    id="bite_fairy_treehouse",
    name="Fairy Treehouse",
    theme="fantasy",
    biome="jungle",
    caption=(
      "a fairy treehouse in a giant jungle tree, octagonal jungle slab platform with "
      "acacia trapdoor banister, birch stair gabled roof, soul lanterns and sandstone walls"
    ),
    palette=(
      "minecraft:jungle_log",
      "minecraft:jungle_slab",
      "minecraft:jungle_stairs",
      "minecraft:acacia_trapdoor",
      "minecraft:sandstone_wall",
      "minecraft:birch_stairs",
      "minecraft:soul_lantern",
      "minecraft:jungle_leaves",
      "minecraft:vine",
      "minecraft:chain",
      "minecraft:acacia_button",
      "minecraft:glass_pane",
      "minecraft:red_sandstone",
    ),
    zones=(
      BuildZone(
        name="treehouse deck",
        size=(11, 1, 11),
        materials=("jungle_slab", "jungle_stairs", "acacia_trapdoor"),
        features=("octagonal deck", "4 blocks above ground", "2x2 jungle trunk"),
        interior=("crafting table", "chest", "ladder", "acacia trapdoor floor hatch"),
      ),
      BuildZone(
        name="roof canopy",
        size=(9, 4, 9),
        materials=("birch_stairs", "jungle_leaves"),
        features=("four-sided birch stair roof", "leaf canopy", "chains and vines"),
        interior=(),
      ),
      BuildZone(
        name="bridge walkway",
        size=(6, 1, 3),
        materials=("acacia_fence_gate", "campfire"),
        features=("linked twin treehouse", "extinguished campfire walkway"),
        interior=(),
      ),
      BuildZone(
        name="enchanting room",
        size=(7, 1, 7),
        materials=("spruce_planks", "glass_pane", "red_sandstone"),
        features=("open-air extension", "sheltered glass room variant"),
        interior=("enchanting table", "bookshelves", "anvil", "grindstone"),
      ),
    ),
    exterior_features=(
      "giant 2x2 jungle tree grown with bone meal",
      "soul lantern ambient lighting",
      "sandstone wall pillars on platform",
      "vines and chains on trunk",
      "acacia button detail on roof",
    ),
    tips=(
      "Grow 2×2 jungle saplings into giant tree before building platform",
      "Platform four blocks above ground using jungle slabs and stairs",
      "Birch stair roofs on all four sides around the trunk",
      "Extension: link two treehouses with acacia gates and campfires",
      "Rated 2-star difficulty, ~45 minutes",
    ),
  ),
  "bite_flying_school": BookBuild(
    id="bite_flying_school",
    name="Superhero Flying School",
    theme="fantasy",
    biome="the_end",
    caption=(
      "a superhero flying school on a floating island, red and white striped marquee "
      "canopy, birch launch deck with water landing pools, obsidian elytra launcher pit"
    ),
    palette=(
      "minecraft:grass_block",
      "minecraft:dirt",
      "minecraft:cobblestone",
      "minecraft:end_stone_bricks",
      "minecraft:end_stone_brick_wall",
      "minecraft:birch_planks",
      "minecraft:birch_slab",
      "minecraft:birch_fence",
      "minecraft:red_wool",
      "minecraft:white_wool",
      "minecraft:obsidian",
      "minecraft:glass_pane",
      "minecraft:white_concrete",
      "minecraft:stone_pressure_plate",
      "minecraft:tnt",
      "minecraft:lantern",
      "minecraft:water",
      "minecraft:large_fern",
      "minecraft:chest",
    ),
    zones=(
      BuildZone(
        name="launch deck",
        size=(17, 1, 17),
        materials=("birch_planks", "birch_slab", "birch_fence"),
        features=("front platform", "water landing pools", "lantern railings"),
        interior=("pig saddle spawn",),
      ),
      BuildZone(
        name="training hall",
        size=(11, 4, 11),
        materials=("end_stone_brick_wall", "birch_planks", "red_wool", "white_wool"),
        features=("open-air marquee", "striped canopy roof", "X-shaped roof opening"),
        interior=("chest", "elytra supplies"),
      ),
      BuildZone(
        name="elytra launcher pit",
        size=(5, 4, 5),
        materials=("obsidian", "water", "tnt", "stone_pressure_plate"),
        features=("5x5 obsidian pit", "center pressure plate", "water cushioned tnt"),
        interior=("tnt charges", "pressure plate trigger"),
      ),
      BuildZone(
        name="observation deck",
        size=(5, 3, 5),
        materials=("glass_pane", "white_concrete"),
        features=("glass control room on roof", "overlooks launch area"),
        interior=(),
      ),
      BuildZone(
        name="walkway",
        size=(5, 1, 8),
        materials=("end_stone_bricks", "birch_planks", "lantern"),
        features=("approach path to marquee", "end stone brick steps"),
        interior=(),
      ),
    ),
    exterior_features=(
      "17x17 floating grass island",
      "red and white wool striped marquee canopy",
      "bamboo perimeter decoration",
      "large ferns around island edge",
      "end stone brick support pillars",
    ),
    tips=(
      "Dig 5×5×4 hole in island center, line with obsidian for elytra launcher",
      "Place TNT around pressure plate, cover with water to protect structure",
      "Red and white wool rings form marquee roof with X opening at top",
      "Glass observation room on roof to watch launches",
      "Rated 3-star difficulty, ~30 minutes",
    ),
  ),
  "bite_item_destroyer": BookBuild(
    id="bite_item_destroyer",
    name="Item Destroyer",
    theme="industrial",
    biome="plains",
    caption=(
      "an item destroyer utility corner, spruce plank and stone brick walls with "
      "embedded chest and barrel input, hidden dropper shoots junk into cactus"
    ),
    palette=(
      "minecraft:spruce_planks",
      "minecraft:stone_bricks",
      "minecraft:grass_block",
      "minecraft:chest",
      "minecraft:barrel",
      "minecraft:hopper",
      "minecraft:dropper",
      "minecraft:comparator",
      "minecraft:observer",
      "minecraft:sticky_piston",
      "minecraft:cactus",
      "minecraft:sand",
      "minecraft:lever",
      "minecraft:torch",
    ),
    zones=(
      BuildZone(
        name="disposal utility room",
        size=(6, 5, 5),
        materials=("spruce_planks", "stone_bricks", "grass_block"),
        features=("corner alcove", "wall-mounted input chest", "decorative barrel", "torch lighting"),
        interior=("chest", "barrel", "hopper", "lever"),
      ),
      BuildZone(
        name="hidden redstone chamber",
        size=(3, 3, 3),
        materials=("dropper", "comparator", "observer", "sticky_piston"),
        features=("auto pulse circuit", "cactus trash destroyer", "behind-wall mechanism"),
        interior=("dropper", "comparator", "observer", "sticky piston", "cactus", "sand"),
      ),
    ),
    exterior_features=(
      "L-shaped spruce and stone brick corner walls",
      "5-block-high utility nook",
      "cactus disposal behind wall",
      "lever on-off switch at hopper",
    ),
    tips=(
      "Walls 5 blocks high — stone brick base, spruce plank top",
      "Hopper under chest feeds dropper; comparator detects items",
      "Observer and sticky piston pulse dropper into cactus on sand",
      "Rated 1-star difficulty, ~5 minutes",
    ),
  ),
  "bite_firefighter_plane": BookBuild(
    id="bite_firefighter_plane",
    name="Firefighter Plane",
    theme="industrial",
    biome="plains",
    caption=(
      "a red and white firefighter flying machine plane, slime block fuselage with "
      "observer piston engine, checkered carpet wings, quartz stair cockpit and minecart seat"
    ),
    palette=(
      "minecraft:slime_block",
      "minecraft:observer",
      "minecraft:sticky_piston",
      "minecraft:quartz_stairs",
      "minecraft:red_carpet",
      "minecraft:white_carpet",
      "minecraft:rail",
      "minecraft:redstone_torch",
      "minecraft:cobblestone",
    ),
    zones=(
      BuildZone(
        name="engine core",
        size=(3, 2, 4),
        materials=("slime_block", "observer", "sticky_piston"),
        features=("flying machine propulsion", "three sticky pistons", "observer pulse chain"),
        interior=("observer", "sticky piston", "slime block frame"),
      ),
      BuildZone(
        name="cockpit",
        size=(2, 2, 2),
        materials=("quartz_stairs", "rail"),
        features=("pilot seat", "minecart passenger seat", "redstone torch start stop"),
        interior=("minecart", "rail", "redstone torch", "quartz stairs"),
      ),
      BuildZone(
        name="wings",
        size=(9, 1, 3),
        materials=("slime_block", "red_carpet", "white_carpet"),
        features=("red white checkered firefighter wings", "slime block extensions"),
        interior=("red carpet", "white carpet"),
      ),
      BuildZone(
        name="tail",
        size=(2, 2, 2),
        materials=("slime_block", "quartz_stairs"),
        features=("rear tail assembly", "stabilizer"),
        interior=(),
      ),
    ),
    exterior_features=(
      "lime green slime block airframe",
      "red and white wool carpet wing checkerboard",
      "redstone flying machine that moves forward in a straight line",
      "firefighter rescue vehicle theme",
    ),
    tips=(
      "Core: observer + sticky piston + slime blocks form the engine",
      "Three pistons push-pull the slime frame within 12-block limit",
      "Place redstone torch on front observer to start, move to stop",
      "Combine with other small builds to make larger scenes",
      "Rated 2-star difficulty, ~10 minutes",
    ),
  ),
  "bite_shooting_gallery": BookBuild(
    id="bite_shooting_gallery",
    name="Shooting Gallery",
    theme="minigame",
    biome="plains",
    caption=(
      "a colorful outdoor shooting gallery minigame, raised blackstone player platform with "
      "spruce railings and chests, grassy target field with disguised redstone target hills, "
      "pink cyan and orange terracotta arcade stalls and a checkered observation tower"
    ),
    palette=(
      "minecraft:grass_block",
      "minecraft:dirt",
      "minecraft:lime_terracotta",
      "minecraft:target",
      "minecraft:redstone_dust",
      "minecraft:redstone_repeater",
      "minecraft:redstone_lamp",
      "minecraft:blackstone",
      "minecraft:blackstone_wall",
      "minecraft:spruce_slab",
      "minecraft:spruce_fence",
      "minecraft:chest",
      "minecraft:lantern",
      "minecraft:pink_terracotta",
      "minecraft:cyan_terracotta",
      "minecraft:orange_terracotta",
      "minecraft:quartz_block",
      "minecraft:dark_oak_stairs",
      "minecraft:oak_leaves",
    ),
    zones=(
      BuildZone(
        name="target mechanism",
        size=(5, 9, 5),
        materials=("lime_terracotta", "target", "redstone_dust", "redstone_repeater", "redstone_lamp"),
        features=("target block", "vertical redstone lamp stack", "repeater delay circuit"),
        interior=("target", "redstone dust", "redstone repeater", "redstone lamp"),
      ),
      BuildZone(
        name="disguised target hill",
        size=(5, 4, 5),
        materials=("grass_block", "dirt", "target", "redstone_lamp"),
        features=("grass-covered redstone hill", "target and lamp visible"),
        interior=("grass block", "dirt"),
      ),
      BuildZone(
        name="target field",
        size=(20, 8, 16),
        materials=("grass_block", "dirt", "oak_leaves", "water"),
        features=("scattered target hills", "ponds", "bushes"),
        interior=(),
      ),
      BuildZone(
        name="shooting gallery platform",
        size=(18, 6, 4),
        materials=("blackstone", "blackstone_wall", "spruce_slab", "spruce_fence", "chest", "lantern"),
        features=("elevated deck", "supply chests", "lantern lighting"),
        interior=("chest", "lantern", "spruce fence"),
      ),
      BuildZone(
        name="arcade stall row",
        size=(12, 8, 6),
        materials=("pink_terracotta", "cyan_terracotta", "orange_terracotta", "quartz_block", "dark_oak_stairs"),
        features=("colorful checkered stalls", "white trim", "dark oak roofs"),
        interior=("lantern",),
      ),
      BuildZone(
        name="observation tower",
        size=(4, 12, 4),
        materials=("cyan_terracotta", "quartz_block", "dark_oak_stairs", "spruce_fence"),
        features=("checkered tower", "roofed balcony", "overlooks the range"),
        interior=("lantern",),
      ),
    ),
    exterior_features=(
      "vertical redstone transmission lights lamps when target is hit",
      "works with bows arrows eggs or splash potions",
      "naturalistic grassy field hides mechanisms",
      "whimsical carnival-style architecture",
    ),
    tips=(
      "5×9 lime terracotta base with target block and redstone dust trail",
      "Repeater on terracotta row delays signal to vertical lamp stack",
      "Cover mechanism in grass and dirt leaving target and lamps visible",
      "Repeat disguised hills across the field; build platform opposite",
      "Rated 2-star difficulty, ~5 minutes per target unit",
    ),
  ),
  "bite_halloween_maze": BookBuild(
    id="bite_halloween_maze",
    name="Halloween Maze",
    theme="halloween",
    biome="plains",
    caption=(
      "a spooky halloween hay bale maze, 16 by 16 winding paths with dead ends, "
      "three-block-tall hay walls, soul campfires and soul torches for blue light, "
      "skull decorations and a carved pumpkin scarecrow in the central courtyard"
    ),
    palette=(
      "minecraft:hay_block",
      "minecraft:dirt",
      "minecraft:mossy_cobblestone",
      "minecraft:oak_fence",
      "minecraft:carved_pumpkin",
      "minecraft:polished_blackstone_button",
      "minecraft:soul_campfire",
      "minecraft:soul_torch",
      "minecraft:oak_trapdoor",
      "minecraft:spruce_trapdoor",
      "minecraft:skeleton_skull",
      "minecraft:zombie_head",
      "minecraft:grass_block",
    ),
    zones=(
      BuildZone(
        name="hay bale maze walls",
        size=(16, 3, 16),
        materials=("hay_block", "oak_trapdoor", "skeleton_skull", "zombie_head"),
        features=("3-block-tall hay walls", "winding dead-end paths", "one entrance one exit"),
        interior=(),
      ),
      BuildZone(
        name="central scarecrow courtyard",
        size=(4, 4, 4),
        materials=("dirt", "mossy_cobblestone", "oak_fence", "carved_pumpkin", "polished_blackstone_button"),
        features=("4x4 central clearing", "pumpkin scarecrow on fence post"),
        interior=("carved pumpkin", "oak fence", "mossy cobblestone"),
      ),
      BuildZone(
        name="soul fire lighting",
        size=(16, 3, 16),
        materials=("soul_campfire", "soul_torch", "oak_fence", "spruce_trapdoor"),
        features=("blue soul campfires in alcoves", "soul torch lamp posts"),
        interior=("soul campfire", "soul torch"),
      ),
    ),
    exterior_features=(
      "16-block square footprint",
      "hay bale walls prevent peeking over",
      "spooky blue soul fire atmosphere",
      "adaptable layout with traps and dead ends",
    ),
    tips=(
      "Lay out a 1-block-tall maze first, then stack to 3 blocks high",
      "Plan winding paths with dead ends — one way in, one way out",
      "Place soul campfires in alcoves and soul torches on fence lamp posts",
      "Central 4×4 courtyard gets a scarecrow: mossy cobblestone, fence, pumpkin",
      "Rated 2-star difficulty, ~30 minutes",
    ),
  ),
  "bite_train_station": BookBuild(
    id="bite_train_station",
    name="Train Station",
    theme="transport",
    biome="plains",
    caption=(
      "a simple two-track train station for a minecraft town, 14 by 9 stone and jungle plank "
      "waiting hall with spruce benches ticket barrier and yellow glass windows, twin platforms "
      "with rails powered rail and bell, anvil railings orange banners and a spruce bridge"
    ),
    palette=(
      "minecraft:stone_bricks",
      "minecraft:stone_brick_slab",
      "minecraft:andesite",
      "minecraft:polished_andesite",
      "minecraft:smooth_quartz",
      "minecraft:smooth_quartz_stairs",
      "minecraft:jungle_planks",
      "minecraft:jungle_slab",
      "minecraft:spruce_planks",
      "minecraft:spruce_stairs",
      "minecraft:spruce_slab",
      "minecraft:diorite",
      "minecraft:yellow_stained_glass_pane",
      "minecraft:iron_trapdoor",
      "minecraft:iron_bars",
      "minecraft:stone_button",
      "minecraft:lantern",
      "minecraft:dark_oak_door",
      "minecraft:dark_oak_trapdoor",
      "minecraft:smooth_stone_slab",
      "minecraft:rail",
      "minecraft:powered_rail",
      "minecraft:activator_rail",
      "minecraft:redstone_torch",
      "minecraft:bell",
      "minecraft:anvil",
      "minecraft:orange_banner",
      "minecraft:chiseled_stone_bricks",
      "minecraft:cobblestone_wall",
      "minecraft:jungle_trapdoor",
      "minecraft:spruce_trapdoor",
      "minecraft:rose_bush",
      "minecraft:dirt",
    ),
    zones=(
      BuildZone(
        name="waiting hall",
        size=(14, 6, 9),
        materials=("jungle_planks", "spruce_stairs", "lantern", "smooth_quartz", "diorite"),
        features=("jungle plank floor", "spruce bench seating", "hanging lanterns"),
        interior=("spruce stairs", "lantern"),
      ),
      BuildZone(
        name="ticket barrier booth",
        size=(4, 4, 2),
        materials=("iron_trapdoor", "smooth_quartz", "stone_button", "diorite", "iron_bars"),
        features=("iron trapdoor gate", "quartz counter", "diorite anti-sneak blocks"),
        interior=("iron trapdoor", "stone button", "iron bars"),
      ),
      BuildZone(
        name="twin track platform",
        size=(18, 3, 10),
        materials=("stone_bricks", "stone_brick_slab", "andesite", "polished_andesite", "anvil", "rail"),
        features=("two parallel rail lines", "stone brick platforms", "anvil safety railing"),
        interior=("rail", "powered rail", "activator rail", "bell"),
      ),
      BuildZone(
        name="jungle roof canopy",
        size=(14, 2, 9),
        materials=("jungle_planks", "jungle_slab", "orange_banner"),
        features=("gabled jungle plank roof", "orange banner trim"),
        interior=("orange banner",),
      ),
      BuildZone(
        name="connecting bridge walkway",
        size=(4, 4, 6),
        materials=("spruce_stairs", "spruce_slab", "jungle_trapdoor"),
        features=("spruce stair bridge", "jungle trapdoor handrail"),
        interior=("spruce stairs", "jungle trapdoor"),
      ),
      BuildZone(
        name="track lighting arch",
        size=(2, 5, 2),
        materials=("chiseled_stone_bricks", "stone_brick_wall", "cobblestone_wall", "lantern"),
        features=("stone arch lantern posts over tracks"),
        interior=("lantern",),
      ),
    ),
    exterior_features=(
      "14-block-long two-track station building",
      "dark oak doors and trapdoors at entrance",
      "stone brick stair caps with exterior lanterns",
      "powered rail departure and bell arrival end",
    ),
    tips=(
      "14×9 foundation: stone border with jungle plank interior floor",
      "Spruce pillar corners, smooth quartz and diorite walls, yellow glass panes",
      "Ticket barrier: iron trapdoor, quartz counter, diorite blocks stop sneaking through",
      "Jungle plank roof with slabs; lay twin rails on smooth stone slab center path",
      "Second platform, anvil railing, bridge, lighting arches, and flowerpot benches",
      "Rated 2-star difficulty, ~35 minutes",
    ),
  ),
  "bite_cart_collector": BookBuild(
    id="bite_cart_collector",
    name="Cart Collector",
    theme="transport",
    biome="plains",
    caption=(
      "a redstone minecart collector for railway stations, rail line rushes carts into a cactus "
      "to break them, hopper line feeds minecart items into a chest for reuse, sticky piston "
      "observer housing with stone slabs and spruce trapdoors"
    ),
    palette=(
      "minecraft:hopper",
      "minecraft:chest",
      "minecraft:rail",
      "minecraft:cactus",
      "minecraft:sand",
      "minecraft:stone",
      "minecraft:grass_block",
      "minecraft:smooth_stone_slab",
      "minecraft:stone_stairs",
      "minecraft:spruce_trapdoor",
      "minecraft:sticky_piston",
      "minecraft:redstone_block",
      "minecraft:observer",
      "minecraft:redstone_dust",
      "minecraft:lantern",
    ),
    zones=(
      BuildZone(
        name="hopper storage line",
        size=(5, 2, 3),
        materials=("hopper", "chest", "stone"),
        features=("four hoppers pointing into chest", "underground item collection"),
        interior=("hopper", "chest"),
      ),
      BuildZone(
        name="cactus breaker mechanism",
        size=(3, 4, 3),
        materials=("cactus", "sand", "sticky_piston", "redstone_block", "observer", "redstone_dust"),
        features=("cactus destroys minecart on impact", "piston observer redstone housing"),
        interior=("cactus", "sand", "sticky piston", "observer", "redstone dust"),
      ),
      BuildZone(
        name="rail approach track",
        size=(9, 2, 4),
        materials=("rail", "stone", "grass_block", "smooth_stone_slab"),
        features=("curved rail into cactus", "9 by 4 platform"),
        interior=("rail",),
      ),
      BuildZone(
        name="drop containment housing",
        size=(3, 3, 3),
        materials=("smooth_stone_slab", "stone_stairs", "spruce_trapdoor"),
        features=("slabs and trapdoors keep cart items from flying away"),
        interior=("smooth stone slab", "spruce trapdoor"),
      ),
    ),
    exterior_features=(
      "9-block-long collector platform",
      "returns minecarts to chest automatically",
      "pairs with train station railway lines",
      "compact underground hopper routing",
    ),
    tips=(
      "Place chest first, then four hoppers with spouts pointing toward it",
      "Build stone and grass platform with hopper chute hole beneath rails",
      "Cactus on sand breaks carts; surround with slabs stairs and trapdoors",
      "Point hopper outputs at the chest so carts return for future use",
      "Rated 2-star difficulty, ~10 minutes",
    ),
  ),
  "bite_bouncy_castle": BookBuild(
    id="bite_bouncy_castle",
    name="Bouncy Castle",
    theme="fantasy",
    biome="plains",
    caption=(
      "a slime-block bouncy castle with smooth red sandstone walls, 14 by 14 cobblestone "
      "foundation, yellow and light blue checkered carpet floors, corner tower with ladder "
      "rampart walkway, soul lanterns and banners"
    ),
    palette=(
      "minecraft:cobblestone",
      "minecraft:dirt",
      "minecraft:slime_block",
      "minecraft:smooth_red_sandstone",
      "minecraft:red_sandstone",
      "minecraft:smooth_red_sandstone_stairs",
      "minecraft:red_sandstone_slab",
      "minecraft:red_sandstone_wall",
      "minecraft:ladder",
      "minecraft:yellow_carpet",
      "minecraft:light_blue_carpet",
      "minecraft:soul_lantern",
      "minecraft:orange_banner",
      "minecraft:light_blue_banner",
    ),
    zones=(
      BuildZone(
        name="bouncy courtyard floor",
        size=(12, 2, 12),
        materials=("slime_block", "dirt", "yellow_carpet", "light_blue_carpet"),
        features=("slime bouncy floor", "yellow and light blue checkered carpet"),
        interior=("slime block", "yellow carpet", "light blue carpet"),
      ),
      BuildZone(
        name="sandstone castle walls",
        size=(14, 6, 14),
        materials=("smooth_red_sandstone", "red_sandstone", "slime_block", "smooth_red_sandstone_stairs"),
        features=("cobblestone outline foundation", "slime layers in walls", "entrance archway"),
        interior=("slime block", "smooth red sandstone stairs"),
      ),
      BuildZone(
        name="rampart walkway",
        size=(14, 2, 14),
        materials=("red_sandstone_slab", "smooth_red_sandstone_stairs", "red_sandstone_wall"),
        features=("upside-down stair lip", "slab walkway around top"),
        interior=("red sandstone slab",),
      ),
      BuildZone(
        name="corner jumping tower",
        size=(4, 10, 4),
        materials=("smooth_red_sandstone", "slime_block", "ladder", "red_sandstone_slab"),
        features=("back corner tower", "ladder climb", "slab jumping platform"),
        interior=("ladder", "red sandstone slab"),
      ),
    ),
    exterior_features=(
      "14-block square bouncy castle footprint",
      "soul lanterns on corner posts",
      "orange and light blue banners at entrance",
      "slime integrated into wall structure for bounce",
    ),
    tips=(
      "14×14 foundation: cobblestone outline with dirt and slime interior",
      "Walls alternate smooth red sandstone, red sandstone, and slime layers",
      "Upside-down smooth red sandstone stairs form entrance archway",
      "Add rampart walkway with slabs and upside-down stairs around exterior",
      "Tower: four more sandstone and slime layers, ladder, slab jumping platform",
      "Decorate with yellow and light blue checkered carpet and soul lanterns",
      "Rated 3-star difficulty, ~35 minutes",
    ),
  ),
  "bite_medieval_windmill": BookBuild(
    id="bite_medieval_windmill",
    name="Medieval Windmill",
    theme="medieval",
    biome="plains",
    caption=(
      "a medieval stone and spruce windmill, 8 by 7 grass base with 5 by 5 cobblestone "
      "foundation, mixed stone brick diorite walls tapering to spruce roof, four white wool "
      "sail vanes on a spruce beam hub, wheat field hay bales and lanterns"
    ),
    palette=(
      "minecraft:grass_block",
      "minecraft:water",
      "minecraft:cobblestone",
      "minecraft:stone_bricks",
      "minecraft:chiseled_stone_bricks",
      "minecraft:polished_diorite",
      "minecraft:diorite",
      "minecraft:diorite_stairs",
      "minecraft:cobblestone_slab",
      "minecraft:cobblestone_wall",
      "minecraft:spruce_planks",
      "minecraft:spruce_stairs",
      "minecraft:spruce_slab",
      "minecraft:spruce_fence",
      "minecraft:spruce_fence_gate",
      "minecraft:spruce_door",
      "minecraft:spruce_button",
      "minecraft:stone_button",
      "minecraft:white_wool",
      "minecraft:wheat",
      "minecraft:hay_block",
      "minecraft:lantern",
      "minecraft:yellow_shulker_box",
    ),
    zones=(
      BuildZone(
        name="stone windmill base",
        size=(5, 4, 5),
        materials=("cobblestone", "stone_bricks", "chiseled_stone_bricks", "polished_diorite"),
        features=("5x5 hollow stone tower", "mixed stone texture walls"),
        interior=(),
      ),
      BuildZone(
        name="spruce entrance porch",
        size=(3, 3, 2),
        materials=("spruce_door", "spruce_stairs", "spruce_fence", "spruce_slab", "cobblestone_wall"),
        features=("spruce door", "pitched stair awning", "fence and slab porch"),
        interior=("spruce door", "spruce stairs"),
      ),
      BuildZone(
        name="tapered wooden tower",
        size=(5, 8, 5),
        materials=("spruce_planks", "diorite", "polished_diorite", "diorite_stairs", "spruce_fence_gate"),
        features=("diamond cobblestone taper", "spruce diorite upper walls", "fence gate windows"),
        interior=("spruce fence gate",),
      ),
      BuildZone(
        name="pitched spruce roof",
        size=(5, 2, 5),
        materials=("cobblestone_slab", "spruce_stairs", "spruce_fence"),
        features=("cobblestone slab ridge", "spruce stair slopes", "hanging corner fences"),
        interior=("spruce stairs", "spruce fence"),
      ),
      BuildZone(
        name="wool sail vanes",
        size=(8, 4, 8),
        materials=("spruce_planks", "spruce_fence", "white_wool", "spruce_button", "stone_button"),
        features=("four cross-shaped sail arms", "white wool sail panels"),
        interior=("white wool", "spruce fence"),
      ),
      BuildZone(
        name="surrounding wheat farm",
        size=(10, 2, 9),
        materials=("wheat", "hay_block", "lantern", "yellow_shulker_box", "water"),
        features=("wheat fields", "hay bale props", "corner water blocks"),
        interior=("hay block", "lantern"),
      ),
    ),
    exterior_features=(
      "8 by 7 grass footprint with water corner blocks",
      "four large white wool windmill blades",
      "buttons on vanes for texture detail",
      "farm scenery with wheat and hay bales",
    ),
    tips=(
      "8×7 grass area; lay 5×5 cobblestone foundation with water at four corners",
      "Build 4-high hollow stone walls mixing cobblestone, stone bricks, and diorite",
      "Spruce door with stair awning; fence gate windows on back wall",
      "Taper with cobblestone diamond layer then spruce wood and diorite stairs",
      "Roof: cobblestone slab ridge with spruce stair slopes on each side",
      "Extend spruce beam hub; build four vanes from wood, fences, and white wool",
      "Rated 2-star difficulty, ~20 minutes",
    ),
  ),
  "bite_portal_toggle": BookBuild(
    id="bite_portal_toggle",
    name="Portal Toggle",
    theme="redstone",
    biome="plains",
    caption=(
      "a toggleable nether portal with obsidian and crying obsidian frame, blackstone decorative "
      "arches, two dispensers with flint and steel and water bucket, redstone repeater sticky "
      "piston and stone button to turn the portal on and off safely"
    ),
    palette=(
      "minecraft:obsidian",
      "minecraft:crying_obsidian",
      "minecraft:blackstone",
      "minecraft:blackstone_stairs",
      "minecraft:dispenser",
      "minecraft:redstone_dust",
      "minecraft:redstone_repeater",
      "minecraft:sticky_piston",
      "minecraft:stone_button",
      "minecraft:grass_block",
      "minecraft:nether_portal",
    ),
    zones=(
      BuildZone(
        name="nether portal frame",
        size=(6, 7, 3),
        materials=("obsidian", "crying_obsidian", "blackstone", "blackstone_stairs"),
        features=("4 by 5 portal opening", "obsidian and crying obsidian mix", "blackstone arch trim"),
        interior=("obsidian", "crying obsidian"),
      ),
      BuildZone(
        name="dispenser toggle circuit",
        size=(9, 3, 3),
        materials=("dispenser", "redstone_dust", "redstone_repeater", "sticky_piston", "stone_button"),
        features=("flint and steel dispenser ignites portal", "water bucket dispenser extinguishes"),
        interior=("dispenser", "redstone dust", "redstone repeater", "sticky piston", "stone button"),
      ),
    ),
    exterior_features=(
      "9 by 3 block footprint, 10 blocks tall",
      "stone button on front face activates toggle",
      "repeater delays water so portal deactivates without flooding",
      "prevents piglins and mobs wandering through when off",
    ),
    tips=(
      "Build 4×5 interior portal frame from obsidian and crying obsidian",
      "Left dispenser: flint and steel to reignite; right dispenser: water bucket to extinguish",
      "Repeater on water side ensures water places then retracts without flooding",
      "Decorate frame with blackstone and blackstone stairs",
      "Rated 2-star difficulty, ~5 minutes",
    ),
  ),
  "bite_outdoor_amphitheatre": BookBuild(
    id="bite_outdoor_amphitheatre",
    name="Outdoor Amphitheatre",
    theme="classical",
    biome="plains",
    caption=(
      "a greco-roman outdoor amphitheatre, 16 by 16 smooth quartz and grass semicircle with "
      "yellow blue concrete and glazed terracotta stage mosaic, tiered cut sandstone seating, "
      "21 quartz pillars, spruce fence trellis with jungle leaves, acacia throne chairs and peony planters"
    ),
    palette=(
      "minecraft:smooth_quartz",
      "minecraft:grass_block",
      "minecraft:yellow_concrete",
      "minecraft:blue_concrete",
      "minecraft:white_glazed_terracotta",
      "minecraft:quartz_block",
      "minecraft:chiseled_quartz_block",
      "minecraft:cut_sandstone_slab",
      "minecraft:smooth_sandstone_stairs",
      "minecraft:quartz_bricks",
      "minecraft:quartz_pillar",
      "minecraft:red_sandstone_wall",
      "minecraft:smooth_quartz_slab",
      "minecraft:smooth_quartz_stairs",
      "minecraft:birch_trapdoor",
      "minecraft:peony",
      "minecraft:acacia_stairs",
      "minecraft:acacia_trapdoor",
      "minecraft:acacia_button",
      "minecraft:spruce_fence",
      "minecraft:jungle_leaves",
      "minecraft:campfire",
      "minecraft:lantern",
      "minecraft:vine",
    ),
    zones=(
      BuildZone(
        name="stage floor mosaic",
        size=(7, 1, 7),
        materials=("yellow_concrete", "blue_concrete", "white_glazed_terracotta", "quartz_block", "chiseled_quartz_block"),
        features=("7 by 7 cross-shaped kaleidoscope pattern", "yellow blue and white terracotta"),
        interior=("yellow concrete", "blue concrete", "white glazed terracotta"),
      ),
      BuildZone(
        name="tiered sandstone seating",
        size=(14, 3, 10),
        materials=("cut_sandstone_slab", "smooth_sandstone_stairs", "quartz_bricks", "quartz_pillar"),
        features=("two curved seating tiers", "smooth sandstone stair benches"),
        interior=("cut sandstone slab", "smooth sandstone stairs"),
      ),
      BuildZone(
        name="quartz pillar colonnade",
        size=(16, 6, 8),
        materials=("quartz_pillar", "quartz_bricks", "chiseled_quartz_block", "red_sandstone_wall"),
        features=("21 quartz pillars around curve", "red sandstone wall infill", "chiseled quartz caps"),
        interior=("quartz pillar", "red sandstone wall"),
      ),
      BuildZone(
        name="acacia throne seating",
        size=(4, 3, 2),
        materials=("acacia_stairs", "acacia_trapdoor"),
        features=("four grand high-backed chairs on top tier"),
        interior=("acacia stairs", "acacia trapdoor"),
      ),
      BuildZone(
        name="spruce trellis canopy",
        size=(14, 3, 10),
        materials=("spruce_fence", "jungle_leaves", "smooth_quartz_slab", "smooth_quartz_stairs", "lantern"),
        features=("spruce fence pergola grid", "jungle leaf shade", "hanging lanterns"),
        interior=("spruce fence", "jungle leaves", "lantern"),
      ),
      BuildZone(
        name="peony planter boxes",
        size=(6, 2, 2),
        materials=("grass_block", "birch_trapdoor", "peony", "campfire", "vine", "acacia_button"),
        features=("birch trapdoor planters with peonies", "campfires around stage edge"),
        interior=("peony", "birch trapdoor", "campfire"),
      ),
    ),
    exterior_features=(
      "16-block circular footprint with smooth quartz rim",
      "semicircular audience bowl facing central stage",
      "vines on pillar sides, acacia buttons on pillar tops",
      "optional pink or glowstone disco stage variants",
    ),
    tips=(
      "16×16 faceted circle: smooth quartz rim, grass interior",
      "Embed 7×7 stage mosaic: yellow and blue concrete, white glazed terracotta, quartz",
      "Two tiers of cut sandstone slabs with smooth sandstone stair benches",
      "Place 21 quartz pillars one block apart around the back curve",
      "Fill gaps with quartz bricks and red sandstone walls; add peony planters",
      "Connect pillar tops with smooth quartz slabs and stairs; spruce fence trellis with jungle leaves",
      "Rated 3-star difficulty, ~45 minutes",
    ),
  ),
  "bite_hidden_bunker": BookBuild(
    id="bite_hidden_bunker",
    name="Hidden Bunker",
    theme="modern",
    biome="plains",
    caption=(
      "an underground hidden bunker, 18 by 18 subterranean base 7 blocks tall with cobblestone "
      "and white concrete walls, birch plank floors, secret sticky piston grass entrance with "
      "ladder shaft, modern kitchen bedroom and living room with tv sofa and dining table"
    ),
    palette=(
      "minecraft:cobblestone",
      "minecraft:stone",
      "minecraft:white_concrete",
      "minecraft:birch_planks",
      "minecraft:birch_stairs",
      "minecraft:birch_slab",
      "minecraft:birch_trapdoor",
      "minecraft:birch_door",
      "minecraft:smooth_quartz_stairs",
      "minecraft:glass_pane",
      "minecraft:ladder",
      "minecraft:grass_block",
      "minecraft:dirt",
      "minecraft:lime_terracotta",
      "minecraft:redstone_dust",
      "minecraft:redstone_repeater",
      "minecraft:redstone_torch",
      "minecraft:sticky_piston",
      "minecraft:lever",
      "minecraft:acacia_stairs",
      "minecraft:orange_carpet",
      "minecraft:black_concrete",
      "minecraft:glowstone",
      "minecraft:jungle_planks",
      "minecraft:jungle_stairs",
      "minecraft:jungle_trapdoor",
      "minecraft:jungle_slab",
      "minecraft:smooth_quartz",
      "minecraft:cauldron",
      "minecraft:iron_block",
      "minecraft:iron_door",
      "minecraft:stone_button",
      "minecraft:smoker",
      "minecraft:chest",
      "minecraft:furnace",
      "minecraft:rail",
      "minecraft:crafting_table",
      "minecraft:brewing_stand",
      "minecraft:white_bed",
      "minecraft:orange_banner",
      "minecraft:sticky_piston",
      "minecraft:gray_carpet",
      "minecraft:birch_pressure_plate",
      "minecraft:spruce_fence",
      "minecraft:bookshelf",
      "minecraft:barrel",
      "minecraft:flower_pot",
      "minecraft:oak_sapling",
      "minecraft:redstone_lamp",
    ),
    zones=(
      BuildZone(
        name="living room lounge",
        size=(10, 7, 8),
        materials=("acacia_stairs", "orange_carpet", "black_concrete", "glowstone", "birch_trapdoor"),
        features=("u-shaped acacia sofa", "wall mounted tv", "recessed glowstone ceiling"),
        interior=("acacia stairs", "orange carpet", "black concrete", "glowstone"),
      ),
      BuildZone(
        name="modern kitchen",
        size=(8, 7, 6),
        materials=("iron_block", "iron_door", "smoker", "smooth_quartz", "cauldron", "furnace", "chest"),
        features=("iron block fridge", "quartz counter with cauldron sinks", "jungle cabinet wall"),
        interior=("iron door", "smoker", "cauldron", "crafting table", "brewing stand"),
      ),
      BuildZone(
        name="bedroom suite",
        size=(8, 7, 6),
        materials=("white_bed", "jungle_planks", "jungle_trapdoor", "orange_banner", "birch_door"),
        features=("queen size double bed", "birch wardrobe", "orange banner pillows"),
        interior=("white bed", "birch door", "orange banner"),
      ),
      BuildZone(
        name="dining lobby",
        size=(8, 7, 6),
        materials=("sticky_piston", "gray_carpet", "jungle_stairs", "birch_pressure_plate", "spruce_fence"),
        features=("piston dining table with grey carpet top", "jungle stair seating"),
        interior=("gray carpet", "jungle stairs", "bookshelf", "chest"),
      ),
      BuildZone(
        name="secret piston entrance",
        size=(5, 12, 5),
        materials=("grass_block", "sticky_piston", "lime_terracotta", "redstone_dust", "redstone_repeater", "lever", "ladder"),
        features=("grass block conceals ladder shaft", "sticky piston toggle", "12 blocks below surface"),
        interior=("sticky piston", "ladder", "redstone dust", "lever"),
      ),
    ),
    exterior_features=(
      "18 by 18 underground footprint dug 12 blocks deep",
      "invisible surface entrance when piston extended",
      "white concrete modern interior with birch accents",
      "glass pane room dividers and raised birch mezzanine",
    ),
    tips=(
      "Dig 12 blocks deep; lay 18×18 stone and cobblestone foundation with birch plank floor",
      "Cobblestone base walls then 4-high white concrete; leave 2×2 ladder corner hole",
      "Ceiling: white concrete with upside-down smooth quartz stairs for recessed lighting",
      "Secret entrance: L-shaped stone platform, lime terracotta redstone path, sticky piston grass cover",
      "Furnish kitchen, bedroom, living room, and dining lobby per household essentials page",
      "Rated 3-star difficulty, ~60 minutes",
    ),
  ),
  "bite_dolphin_fountain": BookBuild(
    id="bite_dolphin_fountain",
    name="Dolphin Fountain",
    theme="aquatic",
    biome="beach",
    caption=(
      "a large dolphin fountain with a leaping prismarine brick dolphin statue, 15 by 15 "
      "octagonal stone brick basin with quartz and prismarine accents, central 5 by 5 pedestal "
      "of dark prismarine slabs and quartz stairs, water flowing into the pool"
    ),
    palette=(
      "minecraft:stone_bricks",
      "minecraft:stone",
      "minecraft:chiseled_stone_bricks",
      "minecraft:dark_prismarine",
      "minecraft:dark_prismarine_slab",
      "minecraft:prismarine",
      "minecraft:prismarine_bricks",
      "minecraft:prismarine_brick_stairs",
      "minecraft:prismarine_brick_slab",
      "minecraft:quartz_block",
      "minecraft:quartz_stairs",
      "minecraft:prismarine_slab",
      "minecraft:water",
      "minecraft:grass_block",
    ),
    zones=(
      BuildZone(
        name="octagonal fountain basin",
        size=(15, 3, 15),
        materials=("stone_bricks", "stone", "chiseled_stone_bricks", "dark_prismarine", "prismarine", "quartz_block", "water"),
        features=("15 by 15 hollow octagonal basin", "quartz inner border", "prismarine rim accents"),
        interior=("water", "quartz block", "prismarine"),
      ),
      BuildZone(
        name="quartz pedestal column",
        size=(5, 6, 5),
        materials=("dark_prismarine_slab", "quartz_stairs", "prismarine_slab", "water"),
        features=("5 by 5 central column", "tiered quartz stairs", "water flows from top"),
        interior=("quartz stairs", "dark prismarine slab", "prismarine slab"),
      ),
      BuildZone(
        name="prismarine dolphin statue",
        size=(11, 7, 5),
        materials=("prismarine_bricks", "prismarine_brick_stairs", "prismarine_brick_slab"),
        features=("11 long 5 wide 7 tall leaping dolphin", "brick stairs and slabs for curves"),
        interior=("prismarine bricks", "prismarine brick stairs", "prismarine brick slab"),
      ),
    ),
    exterior_features=(
      "surface-level fountain in a 1-block-deep trench",
      "lifelike leaping dolphin centerpiece",
      "water cascades from pedestal into basin",
      "chiseled stone accents on outer rim",
    ),
    tips=(
      "Dig 1-block trench; lay 15×15 stone brick and stone octagonal basin rim",
      "Add chiseled stone, dark prismarine, prismarine, and quartz inner border accents",
      "Build 5×5 pedestal: dark prismarine slabs, tiered quartz stairs, prismarine slab cap",
      "Sculpt dolphin: 11×5×7 from prismarine bricks with brick stairs and slabs for curves",
      "Fill basin and let water flow from the pedestal into the pool",
      "Rated 2-star difficulty, ~20 minutes",
    ),
  ),
  "bite_aviary_pyramid": BookBuild(
    id="bite_aviary_pyramid",
    name="Aviary Pyramid",
    theme="nature",
    biome="plains",
    caption=(
      "a glassy aviary pyramid with orange stained glass and polished blackstone brick walls, "
      "14 by 16 grass and quartz brick base, stepped cascading pyramid sides, birch door foyer, "
      "interior jungle tree with fence perches, stone pond and flowers for parrots"
    ),
    palette=(
      "minecraft:grass_block",
      "minecraft:quartz_bricks",
      "minecraft:blackstone",
      "minecraft:polished_blackstone",
      "minecraft:polished_blackstone_bricks",
      "minecraft:polished_blackstone_stairs",
      "minecraft:chiseled_polished_blackstone",
      "minecraft:orange_stained_glass",
      "minecraft:birch_door",
      "minecraft:stone",
      "minecraft:stone_slab",
      "minecraft:stone_stairs",
      "minecraft:jungle_log",
      "minecraft:jungle_leaves",
      "minecraft:jungle_fence",
      "minecraft:water",
      "minecraft:fern",
      "minecraft:red_tulip",
    ),
    zones=(
      BuildZone(
        name="pyramid glass shell",
        size=(14, 8, 16),
        materials=("polished_blackstone_bricks", "orange_stained_glass", "polished_blackstone_stairs", "chiseled_polished_blackstone"),
        features=("stepped cascading pyramid sides", "orange glass panels", "chiseled blackstone roof cap"),
        interior=("orange stained glass", "polished blackstone bricks"),
      ),
      BuildZone(
        name="entrance foyer",
        size=(5, 4, 3),
        materials=("blackstone", "orange_stained_glass", "birch_door", "quartz_bricks"),
        features=("double birch doors", "glass walled foyer porch"),
        interior=("birch door",),
      ),
      BuildZone(
        name="interior pond garden",
        size=(8, 2, 8),
        materials=("stone", "stone_slab", "stone_stairs", "water", "grass_block", "fern", "red_tulip"),
        features=("stone-lined central pond", "grass landscaping", "ferns and tulips"),
        interior=("water", "fern", "red tulip"),
      ),
      BuildZone(
        name="jungle tree perches",
        size=(5, 8, 5),
        materials=("jungle_log", "jungle_leaves", "jungle_fence"),
        features=("custom jungle tree", "six fence post perches on branches"),
        interior=("jungle log", "jungle leaves", "jungle fence"),
      ),
    ),
    exterior_features=(
      "14 by 16 block footprint on grass",
      "blackstone outer ring and quartz brick inner foundation ring",
      "three-block-wide entrance on front face",
      "geometric glass pyramid aviary for parrots",
    ),
    tips=(
      "14×16 base: blackstone outer ring, quartz bricks inside, grass center, 3-wide entrance",
      "Build 2-block walls: polished blackstone brick corners, orange stained glass panels",
      "Step each pyramid ring one block narrower with blackstone stairs on edges",
      "Cap with chiseled polished blackstone; add birch-door foyer at front",
      "Interior: stone pond basin, jungle tree with fence perches, leaves, flowers, water",
      "Rated 2-star difficulty, ~30 minutes",
    ),
  ),
  "bite_deep_sea_submarine": BookBuild(
    id="bite_deep_sea_submarine",
    name="Deep-Sea Submarine",
    theme="aquatic",
    biome="ocean",
    caption=(
      "a deep-sea submarine with light gray concrete cylindrical hull, glass and iron block "
      "cockpit nose, polished andesite tower fin side fins and blast furnace propeller, "
      "nine blocks long with two-block center gap and plus-shaped rear opening"
    ),
    palette=(
      "minecraft:light_gray_concrete",
      "minecraft:glass",
      "minecraft:iron_block",
      "minecraft:polished_andesite",
      "minecraft:polished_andesite_stairs",
      "minecraft:polished_andesite_slab",
      "minecraft:polished_andesite_wall",
      "minecraft:blast_furnace",
      "minecraft:water",
      "minecraft:end_rod",
    ),
    zones=(
      BuildZone(
        name="concrete hull cylinder",
        size=(5, 5, 9),
        materials=("light_gray_concrete",),
        features=("5 by 5 octagonal ring extruded 9 blocks", "2-block hollow center gap"),
        interior=("light gray concrete",),
      ),
      BuildZone(
        name="glass iron cockpit nose",
        size=(3, 3, 2),
        materials=("glass", "iron_block", "light_gray_concrete"),
        features=("glass viewing nose", "iron block frame"),
        interior=("glass", "iron block"),
      ),
      BuildZone(
        name="tower fin sail",
        size=(3, 3, 3),
        materials=("light_gray_concrete", "polished_andesite_stairs", "end_rod"),
        features=("conning tower above 2-block top gap", "andesite stair slopes"),
        interior=("polished andesite stairs", "end rod"),
      ),
      BuildZone(
        name="side fin panels",
        size=(7, 3, 4),
        materials=("polished_andesite", "polished_andesite_stairs", "polished_andesite_slab", "glass"),
        features=("horizontal side fins below tower", "inset andesite panel detailing"),
        interior=("polished andesite stairs", "polished andesite slab"),
      ),
      BuildZone(
        name="blast furnace propeller",
        size=(3, 3, 2),
        materials=("blast_furnace", "polished_andesite_wall", "polished_andesite_slab", "polished_andesite_stairs"),
        features=("blast furnace hub", "four andesite blade arms"),
        interior=("blast furnace", "polished andesite wall"),
      ),
    ),
    exterior_features=(
      "underwater deep ocean build",
      "plus-shaped gap in rear hull wall",
      "polished andesite submarine panel detailing",
      "cylindrical light gray concrete body",
    ),
    tips=(
      "Create 5×5 octagonal hull ring from light gray concrete, extend 9 blocks long",
      "Keep 2-block hollow center gap; back wall leaves a +-shaped opening",
      "Add two more rear wall layers; glass and iron cockpit at the nose",
      "Tower fin on top with polished andesite stairs; side fins from andesite blocks and slabs",
      "Propeller: blast furnace center with andesite stair and wall blades",
      "Rated 4-star difficulty, ~35 minutes",
    ),
  ),
  "bite_underwater_airlock": BookBuild(
    id="bite_underwater_airlock",
    name="Underwater Airlock",
    theme="redstone",
    biome="ocean",
    caption=(
      "an underwater airlock hatch with acacia trapdoor on andesite slab, sticky piston "
      "and polished andesite redstone circuit, lever opens trapdoor to climb into a "
      "submarine without flooding the interior"
    ),
    palette=(
      "minecraft:polished_andesite",
      "minecraft:andesite_stairs",
      "minecraft:andesite_slab",
      "minecraft:acacia_trapdoor",
      "minecraft:sticky_piston",
      "minecraft:redstone_dust",
      "minecraft:redstone_repeater",
      "minecraft:lever",
      "minecraft:stone",
      "minecraft:water",
    ),
    zones=(
      BuildZone(
        name="trapdoor hatch floor",
        size=(3, 2, 3),
        materials=("andesite_slab", "acacia_trapdoor", "polished_andesite"),
        features=("acacia trapdoor entrance", "andesite slab frame"),
        interior=("acacia trapdoor",),
      ),
      BuildZone(
        name="piston redstone circuit",
        size=(3, 3, 6),
        materials=("sticky_piston", "redstone_dust", "redstone_repeater", "andesite_stairs", "lever"),
        features=("sticky piston seal", "lever toggle", "polished andesite dust path"),
        interior=("sticky piston", "redstone dust", "lever"),
      ),
    ),
    exterior_features=(
      "3 by 3 core mechanism footprint",
      "designed to mount on submarine underside",
      "trapdoor auto-closes behind diver",
      "build in air bubble — redstone cannot place underwater",
    ),
    tips=(
      "Use temporary blocks and sponges to create a dry workspace underwater",
      "Polished andesite base with redstone dust path to sticky piston",
      "Andesite stairs connect piston to andesite slab trapdoor hatch",
      "Lever on top toggles open; climb through trapdoor into vessel",
      "Rated 2-star difficulty, ~10 minutes",
    ),
  ),
  "bite_tropical_chalet": BookBuild(
    id="bite_tropical_chalet",
    name="Tropical Beach Chalet",
    theme="tropical",
    biome="beach",
    caption=(
      "a tropical beach chalet on stilts over water, L-shaped 9 by 11 sand and cobblestone base "
      "with oak pillars acacia slab floor, white concrete walls, dark prismarine and acacia "
      "tiered roof, ocean veranda dock campfire area and blue banner interior"
    ),
    palette=(
      "minecraft:sand",
      "minecraft:cobblestone",
      "minecraft:oak_log",
      "minecraft:oak_planks",
      "minecraft:oak_fence",
      "minecraft:oak_door",
      "minecraft:oak_sign",
      "minecraft:acacia_slab",
      "minecraft:acacia_stairs",
      "minecraft:white_concrete",
      "minecraft:gray_concrete",
      "minecraft:smooth_quartz",
      "minecraft:glass_pane",
      "minecraft:dark_prismarine_slab",
      "minecraft:birch_stairs",
      "minecraft:birch_trapdoor",
      "minecraft:scaffolding",
      "minecraft:furnace",
      "minecraft:activator_rail",
      "minecraft:quartz_stairs",
      "minecraft:torch",
      "minecraft:blue_banner",
      "minecraft:bed",
      "minecraft:chest",
      "minecraft:gravel",
      "minecraft:dirt",
      "minecraft:campfire",
      "minecraft:water",
    ),
    zones=(
      BuildZone(
        name="stilt foundation deck",
        size=(9, 4, 11),
        materials=("cobblestone", "sand", "oak_log", "acacia_slab"),
        features=("L-shaped 9x11 base", "ten oak support columns", "acacia slab flooring"),
        interior=("acacia slab", "oak log"),
      ),
      BuildZone(
        name="ocean view veranda",
        size=(9, 3, 4),
        materials=("oak_fence", "birch_stairs", "torch", "oak_planks"),
        features=("deck railing", "birch stair bench", "entrance torches"),
        interior=("birch stairs", "torch"),
      ),
      BuildZone(
        name="tiled kitchen",
        size=(3, 3, 3),
        materials=("white_concrete", "gray_concrete", "furnace", "activator_rail", "quartz_stairs", "scaffolding", "birch_trapdoor"),
        features=("checker concrete tile floor", "furnace stoves with rail burners", "scaffolding tables"),
        interior=("furnace", "activator rail", "quartz stairs"),
      ),
      BuildZone(
        name="bedroom interior",
        size=(6, 4, 6),
        materials=("smooth_quartz", "glass_pane", "blue_banner", "bed", "chest", "oak_door"),
        features=("one-room chalet interior", "blue banners", "bed and chest"),
        interior=("bed", "chest", "blue banner"),
      ),
      BuildZone(
        name="tiered prismarine roof",
        size=(9, 2, 11),
        materials=("dark_prismarine_slab", "acacia_slab", "smooth_quartz"),
        features=("dark prismarine outline", "cascading acacia slab roof"),
        interior=("dark prismarine slab", "acacia slab"),
      ),
      BuildZone(
        name="dock and campfire yard",
        size=(6, 3, 8),
        materials=("oak_planks", "acacia_slab", "torch", "campfire", "gravel", "birch_trapdoor", "dirt"),
        features=("oak dock with torch posts", "sand campfire seating", "gravel entrance path"),
        interior=("campfire", "torch", "acacia slab"),
      ),
    ),
    exterior_features=(
      "elevated over ocean water on cobblestone stilts",
      "oak pergola with sign slats over front veranda",
      "towel rack from oak fence acacia slab and banners",
      "tropical orange and teal roof palette",
    ),
    tips=(
      "L-shaped 9×11 base: sand floor on cobblestone pillars extending to seabed",
      "Ten 2-block oak columns; acacia slab floor with gray white concrete kitchen tiles",
      "White concrete walls, oak log corners, glass pane windows, oak doors",
      "Kitchen stoves: furnace base, activator rail burner, quartz stair hood",
      "Roof: dark prismarine slab outline filled with cascading acacia slabs",
      "Add dock, campfire area, gravel path, and birch trapdoor flower beds",
      "Rated 2-star difficulty, ~25 minutes",
    ),
  ),
  "bite_survivalists_vault": BookBuild(
    id="bite_survivalists_vault",
    name="Survivalist's Vault",
    theme="survival",
    biome="plains",
    caption=(
      "an underground survivalist storage vault, 9 by 9 stone brick room dug nine blocks deep "
      "with sixteen wall chests on two floors, iron bar windows, spruce slab balcony with "
      "trapdoor banister, central campfire cauldron light, anvil grindstone and red banners"
    ),
    palette=(
      "minecraft:stone_bricks",
      "minecraft:cobblestone",
      "minecraft:cobblestone_stairs",
      "minecraft:stone_brick_stairs",
      "minecraft:iron_bars",
      "minecraft:chest",
      "minecraft:ladder",
      "minecraft:lantern",
      "minecraft:polished_blackstone_button",
      "minecraft:anvil",
      "minecraft:grindstone",
      "minecraft:furnace",
      "minecraft:crafting_table",
      "minecraft:cauldron",
      "minecraft:campfire",
      "minecraft:spruce_slab",
      "minecraft:spruce_trapdoor",
      "minecraft:spruce_planks",
      "minecraft:red_banner",
      "minecraft:item_frame",
      "minecraft:dirt",
    ),
    zones=(
      BuildZone(
        name="stone brick vault shell",
        size=(9, 9, 9),
        materials=("stone_bricks", "cobblestone", "cobblestone_stairs", "iron_bars", "stone_brick_stairs"),
        features=("9x9 excavated room", "center wall gaps", "iron bar window slits"),
        interior=("stone bricks", "iron bars"),
      ),
      BuildZone(
        name="ground floor storage wall",
        size=(9, 3, 9),
        materials=("chest", "stone_bricks", "lantern"),
        features=("eight double chests in wall alcoves", "two per side"),
        interior=("chest", "lantern"),
      ),
      BuildZone(
        name="upper balcony storage",
        size=(9, 4, 9),
        materials=("chest", "spruce_slab", "cobblestone_stairs", "spruce_trapdoor", "lantern"),
        features=("second floor spruce slab balcony", "eight more wall chests", "trapdoor banister"),
        interior=("chest", "spruce slab", "spruce trapdoor"),
      ),
      BuildZone(
        name="utility crafting center",
        size=(5, 3, 5),
        materials=("anvil", "grindstone", "furnace", "crafting_table", "cauldron", "campfire", "lantern"),
        features=("central campfire cauldron light", "anvil grindstone furnace crafting table"),
        interior=("anvil", "grindstone", "furnace", "crafting table", "campfire"),
      ),
    ),
    exterior_features=(
      "underground survival storage bunker",
      "corner ladder access between floors",
      "stone brick roof cap",
      "red banner and item frame chest labels",
    ),
    tips=(
      "Dig 9 blocks deep; lay 9×9 cobblestone and stone brick foundation",
      "Build 2-high walls with center gaps; place 8 double chests around perimeter",
      "Add iron bars and upside-down stone brick stair entrance frame",
      "Interior utilities and campfire-on-cauldron centerpiece lighting",
      "Second-floor balcony: spruce slabs, cobblestone stairs, more chests, trapdoor banister",
      "Seal with stone brick roof; label chests with item frames",
      "Rated 2-star difficulty, ~30 minutes",
    ),
  ),
}
