"""
Minecraft Exploded Builds: Medieval Fortress — catalog entries from book photos.

Drop photos in data/book_photos/exploded_fortress/ (or send in chat).
"""

from __future__ import annotations

from .registry import BookBuild, BuildZone

FORTRESS_BUILDS: dict[str, BookBuild] = {
  "fortress_turret": BookBuild(
    id="fortress_turret",
    name="Castle Turret",
    theme="medieval",
    biome="plains",
    caption=(
      "a medieval stone brick castle turret with corner buttress pillars, arrow loop "
      "slits, crenellated battlements, interior spruce plank platforms and a ladder"
    ),
    palette=(
      "minecraft:stone_bricks",
      "minecraft:stone_brick_stairs",
      "minecraft:stone_brick_slab",
      "minecraft:spruce_planks",
      "minecraft:spruce_fence",
      "minecraft:ladder",
      "minecraft:torch",
      "minecraft:grass_block",
    ),
    zones=(
      BuildZone(
        name="stone base platform",
        size=(7, 1, 7),
        materials=("stone_bricks", "stone_brick_slab"),
        features=("7x7 footprint", "raised slab edge trim"),
        interior=(),
      ),
      BuildZone(
        name="corner buttress pillars",
        size=(7, 7, 7),
        materials=("stone_brick_stairs",),
        features=("four corner pillars", "stacked stair texture", "7 blocks tall"),
        interior=(),
      ),
      BuildZone(
        name="tower core",
        size=(5, 12, 5),
        materials=("stone_bricks",),
        features=("5x5 hollow shaft", "arrow loop slits", "12 blocks tall"),
        interior=("ladder",),
      ),
      BuildZone(
        name="interior platforms",
        size=(3, 2, 3),
        materials=("spruce_planks", "ladder"),
        features=("wood plank floors", "ladder between levels"),
        interior=("spruce plank landing", "ladder shaft"),
      ),
      BuildZone(
        name="battlement crown",
        size=(7, 3, 7),
        materials=("stone_bricks", "stone_brick_slab", "spruce_fence", "torch"),
        features=(
          "crenellated parapet",
          "spruce fence corbel supports",
          "corner torches",
        ),
        interior=(),
      ),
    ),
    exterior_features=(
      "stone brick corner buttresses at base",
      "arrow loops for archer cover",
      "crenellated battlements on widened top",
      "torches on corner merlons",
      "grass block foundation pad",
    ),
    tips=(
      "Place at castle wall corners where two walls meet",
      "Use spruce planks and ladders for interior climbing platforms",
      "Stack stone brick stairs vertically for textured corner pillars",
      "Spruce fence posts support the overhanging battlement lip",
      "Variations: obsidian walls, peaked roof, rounded octagonal base, wooden theme",
      "Beginner build, ~30 minutes",
    ),
  ),
  "fortress_outer_wall": BookBuild(
    id="fortress_outer_wall",
    name="Outer Wall",
    theme="medieval",
    biome="plains",
    caption=(
      "an L-shaped medieval castle outer wall corner with stone brick and cobblestone "
      "fortifications, interior spruce plank walkways, arrow slit parapets, wooden "
      "stairs and ladders, oak doors and a cobblestone courtyard path"
    ),
    palette=(
      "minecraft:stone_bricks",
      "minecraft:cobblestone",
      "minecraft:mossy_stone_bricks",
      "minecraft:stone_brick_stairs",
      "minecraft:stone_brick_slab",
      "minecraft:spruce_planks",
      "minecraft:spruce_fence",
      "minecraft:spruce_stairs",
      "minecraft:oak_door",
      "minecraft:ladder",
      "minecraft:torch",
      "minecraft:grass_block",
      "minecraft:dirt",
      "minecraft:oxeye_daisy",
    ),
    zones=(
      BuildZone(
        name="corner tower",
        size=(5, 8, 5),
        materials=("stone_bricks", "cobblestone", "mossy_stone_bricks"),
        features=("5x5 corner block", "crenellated top", "oak door entrance"),
        interior=("ladder", "spruce stairs"),
      ),
      BuildZone(
        name="wall arm north",
        size=(11, 8, 3),
        materials=("stone_bricks", "cobblestone"),
        features=("11 blocks long", "3 blocks thick", "arrow slits", "8 blocks tall"),
        interior=("interior corridor",),
      ),
      BuildZone(
        name="wall arm east",
        size=(3, 8, 11),
        materials=("stone_bricks", "cobblestone"),
        features=("11 blocks long", "3 blocks thick", "arrow slits", "8 blocks tall"),
        interior=("interior corridor",),
      ),
      BuildZone(
        name="battlement walkway",
        size=(16, 2, 16),
        materials=("spruce_planks", "spruce_fence", "stone_brick_slab"),
        features=(
          "parapet sheltered walkway",
          "crenellated merlons and crenels",
          "fence railings on inner edge",
        ),
        interior=(),
      ),
      BuildZone(
        name="courtyard interior",
        size=(10, 1, 10),
        materials=("grass_block", "cobblestone", "dirt"),
        features=("enclosed courtyard", "cobblestone path", "oxeye daisy flowers"),
        interior=(),
      ),
    ),
    exterior_features=(
      "L-shaped corner fortification connecting two wall arms",
      "arrow slits on exterior faces for archer cover",
      "crenellated parapet with merlons and crenels",
      "spruce plank wall-top walkway with fence railings",
      "interior ladders and stairs for quick troop access",
      "cobblestone path through enclosed courtyard",
    ),
    tips=(
      "Extend walls from turrets at each fortress corner",
      "Interior wall paths let soldiers move without arrow exposure",
      "Ladders every few blocks speed access to battlements",
      "Variations: obsidian and water indestructible wall, lava or cactus moat, stone drawbridge",
      "Parapet protects anyone walking along the wall top",
      "Easy build, ~1.5 hours",
    ),
  ),
  "fortress_portcullis": BookBuild(
    id="fortress_portcullis",
    name="Portcullis Gatehouse",
    theme="medieval",
    biome="plains",
    caption=(
      "a medieval castle portcullis gatehouse with spruce fence drop gate, gravel "
      "counterweight column, redstone piston pulley system, stone brick walls with "
      "crenellations and arrow slits, lever-controlled entrance"
    ),
    palette=(
      "minecraft:stone_bricks",
      "minecraft:cobblestone",
      "minecraft:stone_brick_slab",
      "minecraft:spruce_fence",
      "minecraft:spruce_planks",
      "minecraft:gravel",
      "minecraft:piston",
      "minecraft:sticky_piston",
      "minecraft:redstone_torch",
      "minecraft:redstone_repeater",
      "minecraft:redstone_dust",
      "minecraft:lever",
      "minecraft:hopper",
      "minecraft:dropper",
      "minecraft:torch",
      "minecraft:grass_block",
    ),
    zones=(
      BuildZone(
        name="gatehouse walls",
        size=(14, 10, 7),
        materials=("stone_bricks", "cobblestone", "stone_brick_slab"),
        features=(
          "14-block-wide gatehouse",
          "crenellated battlements",
          "arrow slit windows",
          "flanking side towers",
        ),
        interior=(),
      ),
      BuildZone(
        name="portcullis gate",
        size=(8, 6, 1),
        materials=("spruce_fence", "gravel"),
        features=(
          "8-wide fence grid gate",
          "gravel counterweight row",
          "2-block passage when raised",
        ),
        interior=(),
      ),
      BuildZone(
        name="redstone engine",
        size=(13, 6, 3),
        materials=(
          "piston",
          "sticky_piston",
          "redstone_torch",
          "redstone_repeater",
          "redstone_dust",
          "lever",
          "hopper",
          "dropper",
        ),
        features=(
          "dual piston rows push gate up and down",
          "redstone torch tower vertical signal",
          "dropper hopper comparator timing circuit",
          "3-block-deep foundation pit",
        ),
        interior=("lever control", "redstone repeater sequences"),
      ),
      BuildZone(
        name="upper guard floor",
        size=(14, 1, 7),
        materials=("spruce_planks", "torch"),
        features=("interior plank floor", "guard walkway above gate"),
        interior=("torch lighting",),
      ),
    ),
    exterior_features=(
      "heavy spruce fence portcullis gate in stone archway",
      "gravel counterweight column beside gate",
      "crenellated stone gatehouse with torches",
      "arrow slits on flanking tower walls",
      "concealed redstone mechanism in wall thickness",
      "grass block approach path",
    ),
    tips=(
      "Gate is 8 blocks wide with 2-block clearance when open",
      "Mechanism needs 14-block-wide wall section and 3-block-deep pit",
      "Gravel falls when unsupported — powers up/down piston sequences",
      "Dropper and hopper circuit controls top downward pistons",
      "Quick-release latch can drop gate instantly under attack",
      "Experienced build, ~2 hours",
    ),
  ),
  "fortress_keep": BookBuild(
    id="fortress_keep",
    name="Castle Keep",
    theme="medieval",
    biome="plains",
    caption=(
      "a medieval castle keep citadel with four corner towers, crenellated stone brick "
      "battlements, spruce plank roof deck, central lookout tower, recessed entrance "
      "with bridge, red carpet interior halls and arrow slit windows"
    ),
    palette=(
      "minecraft:stone_bricks",
      "minecraft:mossy_stone_bricks",
      "minecraft:cracked_stone_bricks",
      "minecraft:chiseled_stone_bricks",
      "minecraft:cobblestone",
      "minecraft:stone_brick_stairs",
      "minecraft:stone_brick_slab",
      "minecraft:spruce_planks",
      "minecraft:spruce_fence",
      "minecraft:spruce_door",
      "minecraft:red_carpet",
      "minecraft:white_carpet",
      "minecraft:red_banner",
      "minecraft:torch",
      "minecraft:grass_block",
      "minecraft:dirt",
      "minecraft:bookshelf",
      "minecraft:red_bed",
    ),
    zones=(
      BuildZone(
        name="main keep shell",
        size=(12, 10, 12),
        materials=(
          "stone_bricks",
          "mossy_stone_bricks",
          "cracked_stone_bricks",
          "chiseled_stone_bricks",
        ),
        features=(
          "12x12 square footprint",
          "thick stone walls",
          "arrow slit windows",
          "putlog holes in walls",
        ),
        interior=("red carpet halls",),
      ),
      BuildZone(
        name="corner towers",
        size=(3, 12, 3),
        materials=("stone_bricks", "mossy_stone_bricks", "chiseled_stone_bricks"),
        features=("four protruding corner towers", "crenellated tops", "banner flags"),
        interior=("ladder access",),
      ),
      BuildZone(
        name="battlement roof deck",
        size=(12, 2, 12),
        materials=("spruce_planks", "stone_brick_slab", "spruce_fence", "torch"),
        features=(
          "flat walking battlement",
          "stone stair corbel overhang",
          "crenellated merlons",
          "central lookout tower",
        ),
        interior=(),
      ),
      BuildZone(
        name="entrance bridge",
        size=(5, 3, 3),
        materials=("stone_bricks", "stone_brick_stairs", "cobblestone", "spruce_door"),
        features=("recessed main gate", "stone bridge approach", "torch-lit doorway"),
        interior=(),
      ),
      BuildZone(
        name="interior rooms",
        size=(8, 4, 8),
        materials=("red_carpet", "white_carpet", "bookshelf", "red_bed"),
        features=(
          "royal bedchamber",
          "library bookcases",
          "guest quarters",
          "dining hall",
        ),
        interior=("four-poster bed", "bookshelves", "red beds", "dining table area"),
      ),
      BuildZone(
        name="tiered hill base",
        size=(16, 3, 16),
        materials=("grass_block", "dirt", "cobblestone", "stone"),
        features=("elevated grassy hill", "tiered terrain", "stone foundation"),
        interior=(),
      ),
    ),
    exterior_features=(
      "four corner towers at different heights",
      "crenellated battlement walkway on roof",
      "central elevated lookout tower",
      "red and white banner flags on towers",
      "stone brick entrance bridge over tiered hill",
      "spruce fence torch posts on battlements",
    ),
    tips=(
      "Centerpiece citadel of the fortress — ruler's home",
      "Use mossy and cracked stone bricks for aged texture",
      "Stone brick stairs create corbel overhang under battlements",
      "Ground floor reserved for throne room and entrance",
      "Variations: Germanic style wood roofs, TNT cannon defenses on roof",
      "Intermediate build, ~4 hours",
    ),
  ),
  "fortress_throne_room": BookBuild(
    id="fortress_throne_room",
    name="Throne Room",
    theme="medieval",
    biome="plains",
    caption=(
      "a medieval castle throne room with raised stone plinth, spruce wood throne "
      "with skeleton skulls, red carpet runner, wooden balcony overlook, chiseled "
      "stone brick walls and torch-lit spruce fence wall sconces"
    ),
    palette=(
      "minecraft:stone_bricks",
      "minecraft:chiseled_stone_bricks",
      "minecraft:cracked_stone_bricks",
      "minecraft:stone",
      "minecraft:stone_brick_stairs",
      "minecraft:stone_brick_slab",
      "minecraft:spruce_stairs",
      "minecraft:spruce_slab",
      "minecraft:spruce_fence",
      "minecraft:spruce_door",
      "minecraft:spruce_planks",
      "minecraft:red_carpet",
      "minecraft:red_terracotta",
      "minecraft:red_stained_glass_pane",
      "minecraft:glass_pane",
      "minecraft:skeleton_skull",
      "minecraft:painting",
      "minecraft:torch",
    ),
    zones=(
      BuildZone(
        name="throne hall",
        size=(11, 5, 12),
        materials=("stone_bricks", "chiseled_stone_bricks", "cracked_stone_bricks", "stone"),
        features=(
          "11x12 rectangular hall",
          "5-block ceiling height",
          "red carpet central runner",
          "red terracotta floor accents",
        ),
        interior=("red carpet aisle", "stone floor"),
      ),
      BuildZone(
        name="throne plinth",
        size=(5, 3, 2),
        materials=("stone_brick_stairs", "stone_brick_slab", "spruce_stairs"),
        features=(
          "cascading stepped dais",
          "stone brick stair surround",
          "spruce wood throne chair",
          "skeleton skull trophies",
        ),
        interior=("spruce stair throne", "skeleton skulls"),
      ),
      BuildZone(
        name="royal balcony",
        size=(4, 2, 3),
        materials=("spruce_planks", "spruce_fence", "spruce_door"),
        features=("elevated wooden balcony", "fence railings", "overlooks throne"),
        interior=(),
      ),
      BuildZone(
        name="inspiration ornamentation style",
        size=(0, 0, 0),
        materials=(
          "stone_bricks",
          "chiseled_stone_bricks",
          "cobblestone_wall",
          "dark_oak_stairs",
          "red_carpet",
          "yellow_carpet",
          "light_blue_stained_glass",
          "yellow_stained_glass",
          "end_rod",
          "green_banner",
        ),
        features=(
          "red and yellow checkerboard carpet floor",
          "tall pillar capitals from cobblestone walls",
          "stained glass tall windows",
          "end rod candle lighting",
          "zombie head banners behind throne",
        ),
        interior=("ornate pillars", "shield wall mounts", "high ceiling"),
      ),
      BuildZone(
        name="inspiration war room style",
        size=(0, 0, 0),
        materials=(
          "stone_bricks",
          "dark_oak_log",
          "dark_oak_planks",
          "piston",
          "yellow_carpet",
          "white_carpet",
          "netherrack",
          "fire",
        ),
        features=(
          "dark oak ceiling beams",
          "piston-head strategy table with carpet checkerboard",
          "recessed netherrack fire wall alcoves",
          "candles on strategy table",
        ),
        interior=("raid planning table", "war council seating"),
      ),
      BuildZone(
        name="inspiration royal court style",
        size=(0, 0, 0),
        materials=(
          "stone_bricks",
          "spruce_log",
          "spruce_planks",
          "red_carpet",
          "glowstone",
          "spruce_fence",
        ),
        features=(
          "two-story court with wooden balcony",
          "red carpet pleading platform",
          "glowstone throne backdrop lighting",
          "log pillar supports",
        ),
        interior=("public ground floor", "royal upper balcony"),
      ),
      BuildZone(
        name="inspiration royal seat style",
        size=(0, 0, 0),
        materials=(
          "gold_block",
          "yellow_stained_glass",
          "birch_stairs",
          "water",
          "quartz_block",
          "black_wool",
          "iron_bars",
          "redstone_torch",
        ),
        features=(
          "gold block and yellow glass towering throne",
          "black white checkerboard floor",
          "water moat around throne with fence border",
          "iron bar wall recesses",
          "head statues on pedestals",
        ),
        interior=("opulent gold throne", "personal moat"),
      ),
      BuildZone(
        name="inspiration infernal throne style",
        size=(0, 0, 0),
        materials=(
          "obsidian",
          "iron_block",
          "iron_stairs",
          "cobblestone",
          "netherrack",
          "lava",
          "dark_oak_log",
          "redstone_torch",
          "dark_oak_fence",
        ),
        features=(
          "obsidian floor border",
          "corner lava pits",
          "iron block throne on netherrack dais",
          "dark oak log pillars with iron bars",
          "redstone torch eerie lighting",
        ),
        interior=("menacing iron throne", "lava corner pits"),
      ),
    ),
    exterior_features=(
      "stone brick hall with chiseled corner accents",
      "red stained glass regal windows",
      "spruce fence torch wall sconces",
      "painting between entrance doors",
      "raised throne plinth above floor level",
    ),
    tips=(
      "Medieval monarchies often had dual thrones for king and queen",
      "Raise thrones on plinths so rulers sit above the room",
      "Mix stone brick, chiseled and cracked blocks for wall texture",
      "Plinth uses cascading blocks surrounded by stone brick stairs",
      "Variation palettes: ornamentation red/yellow carpet + end rods",
      "Variation palettes: war room dark oak beams + piston strategy table",
      "Variation palettes: royal court balcony + glowstone throne light",
      "Variation palettes: royal seat gold blocks + water moat + checkerboard",
      "Variation palettes: infernal obsidian + lava pits + iron throne",
      "Beginner build, ~30 minutes",
    ),
  ),
  "fortress_barracks": BookBuild(
    id="fortress_barracks",
    name="Barracks",
    theme="medieval",
    biome="plains",
    caption=(
      "a medieval castle barracks with cobblestone foundation, stone brick ground "
      "floor, diorite and dark oak upper story, spruce peaked roof, sand training "
      "courtyard with fence, loft beds and chest storage"
    ),
    palette=(
      "minecraft:cobblestone",
      "minecraft:stone_bricks",
      "minecraft:diorite",
      "minecraft:dark_oak_log",
      "minecraft:dark_oak_stairs",
      "minecraft:dark_oak_fence",
      "minecraft:dark_oak_door",
      "minecraft:spruce_planks",
      "minecraft:spruce_stairs",
      "minecraft:spruce_fence",
      "minecraft:sand",
      "minecraft:glass_pane",
      "minecraft:ladder",
      "minecraft:red_bed",
      "minecraft:chest",
      "minecraft:torch",
      "minecraft:redstone_lamp",
      "minecraft:hay_block",
      "minecraft:grass_block",
    ),
    zones=(
      BuildZone(
        name="barracks building",
        size=(10, 6, 8),
        materials=(
          "cobblestone",
          "stone_bricks",
          "diorite",
          "dark_oak_log",
          "spruce_stairs",
          "spruce_planks",
        ),
        features=(
          "two-story soldier quarters",
          "spruce peaked roof overhang",
          "diorite tudor upper walls",
          "dark oak timber frame",
        ),
        interior=("red beds", "chests", "ladder"),
      ),
      BuildZone(
        name="training courtyard",
        size=(6, 1, 5),
        materials=("sand", "dark_oak_fence", "redstone_lamp"),
        features=(
          "outdoor sand practice yard",
          "fence enclosed courtyard",
          "archery target area",
        ),
        interior=("redstone lamp target",),
      ),
      BuildZone(
        name="roof balcony",
        size=(3, 2, 3),
        materials=("spruce_planks", "dark_oak_fence", "torch", "chest"),
        features=("flat roof balcony", "fence railings", "storage chest"),
        interior=(),
      ),
      BuildZone(
        name="inspiration castle annex",
        size=(0, 0, 0),
        materials=(
          "stone_bricks",
          "cobblestone",
          "oak_planks",
          "dark_oak_fence",
          "stone_brick_stairs",
          "red_bed",
          "chest",
          "redstone_lamp",
          "crafting_table",
        ),
        features=(
          "multi-level annex attached to keep",
          "sleeping quarters with row of beds",
          "strategy and practice rooms",
          "redstone lamp arrow target",
        ),
        interior=("bunk sleeping floor", "armor stand lookout", "crafting room"),
      ),
      BuildZone(
        name="inspiration animal sheds",
        size=(0, 0, 0),
        materials=(
          "oak_planks",
          "cobblestone",
          "dark_oak_stairs",
          "dark_oak_slab",
          "dark_oak_fence",
          "dark_oak_fence_gate",
          "hay_block",
          "iron_bars",
        ),
        features=(
          "horse stable stalls with hay bales",
          "wolf kennel pens",
          "chests for horse armor storage",
          "iron bar stable windows",
        ),
        interior=("hay bale stalls", "animal pens"),
      ),
      BuildZone(
        name="inspiration forge",
        size=(0, 0, 0),
        materials=(
          "stone_bricks",
          "dark_oak_stairs",
          "netherrack",
          "fire",
          "anvil",
          "furnace",
          "crafting_table",
          "chest",
        ),
        features=(
          "open-sided blacksmith workshop",
          "stone brick chimney with netherrack hearth",
          "anvil repair station",
          "weapon and armor crafting area",
        ),
        interior=("anvils", "furnaces", "flaming hearth"),
      ),
      BuildZone(
        name="inspiration training arena",
        size=(0, 0, 0),
        materials=(
          "sand",
          "stone_brick_stairs",
          "spruce_log",
          "dark_oak_planks",
          "yellow_terracotta",
          "red_banner",
          "ladder",
          "torch",
        ),
        features=(
          "sunken octagonal combat pit",
          "tiered stone stair seating",
          "yellow terracotta wall stripe",
          "red banner perimeter decor",
        ),
        interior=("sparring pit", "viewing deck"),
      ),
      BuildZone(
        name="inspiration dormitory",
        size=(0, 0, 0),
        materials=(
          "stone_bricks",
          "dark_oak_stairs",
          "spruce_slab",
          "red_bed",
          "chest",
          "armor_stand",
          "item_frame",
        ),
        features=(
          "bunk beds using wall slabs",
          "row of armor stands",
          "chest storage at bed feet",
          "item frame weapon displays",
        ),
        interior=("bunk beds", "armor stand row", "weapon racks"),
      ),
    ),
    exterior_features=(
      "cobblestone foundation in castle bailey ward",
      "sand training courtyard with fence enclosure",
      "spruce stair roof with single-block overhang",
      "upper floor diorite and dark oak tudor style",
      "hay bale lean-to side extension",
      "roof balcony with chest and torches",
    ),
    tips=(
      "Build within castle walls but outside the keep in the bailey",
      "Combine interior living with outdoor practice courtyard",
      "Stair blocks join seamlessly around unusual roof corners",
      "Roof should overhang walls by one block",
      "Variation: castle annex multi-level attached to keep",
      "Variation: animal sheds with hay stalls and horse armor chests",
      "Variation: forge with netherrack chimney hearth and anvils",
      "Variation: sunken training arena with terracotta stripe walls",
      "Variation: dormitory bunk beds on wall slabs to save space",
      "Easy build, ~1 hour",
    ),
  ),
  "fortress_enchanting_room": BookBuild(
    id="fortress_enchanting_room",
    name="Enchanting Room",
    theme="medieval",
    biome="plains",
    caption=(
      "a medieval castle enchanting room with nether brick enchantment platform, "
      "bookshelf U-shape around enchanting table, spruce wood balcony overlook, "
      "brewing stand and cauldron, stone brick and red nether brick walls"
    ),
    palette=(
      "minecraft:stone_bricks",
      "minecraft:nether_bricks",
      "minecraft:nether_brick_slab",
      "minecraft:red_nether_bricks",
      "minecraft:spruce_planks",
      "minecraft:spruce_fence",
      "minecraft:spruce_slab",
      "minecraft:dark_oak_planks",
      "minecraft:bookshelf",
      "minecraft:enchanting_table",
      "minecraft:brewing_stand",
      "minecraft:cauldron",
      "minecraft:chest",
      "minecraft:glass_pane",
      "minecraft:ladder",
      "minecraft:painting",
      "minecraft:torch",
    ),
    zones=(
      BuildZone(
        name="enchantment platform",
        size=(5, 3, 5),
        materials=("nether_bricks", "bookshelf", "enchanting_table"),
        features=(
          "5x5 nether brick raised platform",
          "15 bookshelves for level 30 enchanting",
          "U-shaped bookshelf arrangement",
        ),
        interior=("enchanting table",),
      ),
      BuildZone(
        name="enchanting hall",
        size=(10, 7, 9),
        materials=(
          "stone_bricks",
          "spruce_planks",
          "red_nether_bricks",
          "dark_oak_planks",
        ),
        features=(
          "two-story scholarly chamber",
          "red nether brick wall stripes",
          "oak ceiling beams",
          "glass pane windows",
        ),
        interior=("paintings", "torches"),
      ),
      BuildZone(
        name="brewing balcony",
        size=(9, 2, 4),
        materials=("spruce_planks", "spruce_fence", "ladder", "brewing_stand", "cauldron"),
        features=(
          "L-shaped upper balcony walkway",
          "spruce fence railing",
          "ladder access from ground floor",
        ),
        interior=("brewing stand counter", "cauldron"),
      ),
      BuildZone(
        name="inspiration hidden library",
        size=(0, 0, 0),
        materials=(
          "oak_planks",
          "oak_slab",
          "bookshelf",
          "sticky_piston",
          "redstone_dust",
          "stone_pressure_plate",
          "enchanting_table",
        ),
        features=(
          "levitating bookshelf ring on sticky pistons",
          "pressure plate triggers bookshelf rise",
          "redstone lattice under floor",
          "hidden bookshelves retract when empty",
        ),
        interior=("retractable bookshelf floor", "enchanting table"),
      ),
      BuildZone(
        name="inspiration potion dispensers",
        size=(0, 0, 0),
        materials=(
          "stone_bricks",
          "oak_planks",
          "oak_slab",
          "dispenser",
          "item_frame",
          "stone_button",
          "brewing_stand",
          "cauldron",
          "chest",
        ),
        features=(
          "labeled potion dispenser wall",
          "oak loft storage platforms",
          "mass potion brewing laboratory",
          "item frame potion labels",
        ),
        interior=("dispenser wall", "brewing stations", "chest lofts"),
      ),
      BuildZone(
        name="inspiration wizard tower",
        size=(0, 0, 0),
        materials=(
          "stone_bricks",
          "mossy_stone_bricks",
          "dark_oak_planks",
          "bookshelf",
          "enchanting_table",
          "glowstone",
          "iron_bars",
        ),
        features=(
          "multi-story vertical wizard tower",
          "glowstone chandelier lighting",
          "dark oak interior wall lining",
          "bookshelf study levels",
        ),
        interior=("enchanting study", "glowstone chandeliers", "storage floor"),
      ),
      BuildZone(
        name="inspiration nether room",
        size=(0, 0, 0),
        materials=(
          "nether_bricks",
          "nether_brick_stairs",
          "nether_brick_slab",
          "obsidian",
          "netherrack",
          "fire",
          "dark_oak_planks",
          "bookshelf",
          "brewing_stand",
        ),
        features=(
          "obsidian nether portal centerpiece",
          "sunken stone brick floor center",
          "netherrack fire corner lighting",
          "nether brick raised perimeter",
          "ghast banner wall decor",
        ),
        interior=("nether portal", "brewing nook", "enchanting library corner"),
      ),
    ),
    exterior_features=(
      "stone brick and spruce plank layered walls",
      "red nether brick decorative stripes",
      "nether brick enchantment floor border",
      "upper balcony with fence railings and torches",
      "medieval scholarly wizard study aesthetic",
    ),
    tips=(
      "Place 15 bookshelves in U-shape for maximum enchantment level",
      "5x5 nether brick platform elevates the enchantment table",
      "Combine enchanting with brewing stand and cauldron station",
      "L-shaped balcony provides overhead view of enchanting floor",
      "Variation: hidden library with sticky piston rising bookshelves",
      "Variation: potion dispenser wall with labeled item frames",
      "Variation: wizard tower with glowstone chandeliers",
      "Variation: nether room with portal and netherrack fire pits",
      "Easy build, ~1 hour",
    ),
  ),
  "fortress_dungeon": BookBuild(
    id="fortress_dungeon",
    name="Dungeon",
    theme="medieval",
    biome="plains",
    caption=(
      "an underground castle dungeon with iron bar prison cells, mossy cobblestone "
      "and stone brick walls, guard station with spruce fence desk, iron doors, "
      "red beds, cauldron and torch-lit corridors beneath the keep"
    ),
    palette=(
      "minecraft:cobblestone",
      "minecraft:mossy_cobblestone",
      "minecraft:stone_bricks",
      "minecraft:mossy_stone_bricks",
      "minecraft:andesite",
      "minecraft:smooth_stone",
      "minecraft:iron_bars",
      "minecraft:iron_door",
      "minecraft:spruce_fence",
      "minecraft:spruce_fence_gate",
      "minecraft:spruce_trapdoor",
      "minecraft:ladder",
      "minecraft:chest",
      "minecraft:red_bed",
      "minecraft:cauldron",
      "minecraft:torch",
      "minecraft:redstone_dust",
    ),
    zones=(
      BuildZone(
        name="prison cell block",
        size=(12, 4, 11),
        materials=(
          "cobblestone",
          "mossy_cobblestone",
          "stone_bricks",
          "mossy_stone_bricks",
          "andesite",
          "iron_bars",
          "iron_door",
        ),
        features=(
          "multiple iron bar cells",
          "6x7 cell footprint",
          "iron door entrances",
          "arrow slit windows",
        ),
        interior=("red beds", "cauldrons", "redstone blood trails"),
      ),
      BuildZone(
        name="guard station",
        size=(4, 3, 4),
        materials=("spruce_fence", "spruce_fence_gate", "chest", "torch"),
        features=("spruce fence guard desk", "chest storage", "central corridor watch"),
        interior=("guard desk", "chest"),
      ),
      BuildZone(
        name="lower cavern level",
        size=(10, 3, 8),
        materials=("stone", "cobblestone", "ladder", "spruce_trapdoor"),
        features=("ladder access hole", "trapdoor floor hatch", "dark lower level"),
        interior=(),
      ),
      BuildZone(
        name="inspiration impenetrable cells",
        size=(0, 0, 0),
        materials=(
          "obsidian",
          "lava",
          "stone_bricks",
          "dark_oak_slab",
          "ladder",
          "iron_bars",
          "iron_door",
          "lever",
          "red_bed",
        ),
        features=(
          "lava-filled triple layer walls",
          "obsidian inner obsidian shell",
          "bunk bed platforms on wall slabs",
          "lever controlled iron doors",
        ),
        interior=("wall bunk beds", "lava curtain walls"),
      ),
      BuildZone(
        name="inspiration oubliette pit",
        size=(0, 0, 0),
        materials=(
          "obsidian",
          "stone_bricks",
          "oak_planks",
          "iron_bars",
          "oak_trapdoor",
          "lever",
          "torch",
        ),
        features=(
          "obsidian isolation pit",
          "ceiling trapdoor entrance",
          "lever controlled drop hatch",
          "iron bar observation window",
        ),
        interior=("lonely pit cell",),
      ),
      BuildZone(
        name="inspiration basic dungeon",
        size=(0, 0, 0),
        materials=(
          "dirt",
          "cobblestone",
          "oak_planks",
          "oak_log",
          "iron_bars",
          "red_bed",
          "oak_fence",
          "torch",
        ),
        features=(
          "dirt and cobblestone patchwork walls",
          "makeshift iron bar alcove cells",
          "torch on fence post floor lamps",
          "deep underground dirt-walled prison",
        ),
        interior=("red beds on floor",),
      ),
      BuildZone(
        name="inspiration torture chamber",
        size=(0, 0, 0),
        materials=(
          "stone_bricks",
          "mossy_stone_bricks",
          "cracked_stone_bricks",
          "oak_stairs",
          "oak_slab",
          "oak_fence",
          "iron_bars",
          "iron_block",
          "anvil",
          "cauldron",
          "netherrack",
          "redstone_dust",
          "lever",
          "torch",
        ),
        features=(
          "oak wood stretch rack with levers",
          "iron block iron maiden",
          "dunking stool over floor hole",
          "raised observation walkway",
          "redstone dust blood stains",
          "cauldron over netherrack fire",
        ),
        interior=("stretch rack", "iron maiden", "anvil", "iron bar cages"),
      ),
    ),
    exterior_features=(
      "underground beneath castle keep",
      "mixed mossy stone texture walls",
      "iron bar cell fronts and slit windows",
      "spruce fence guard desk barrier",
      "ladder and trapdoor to lower cavern",
    ),
    tips=(
      "Build beneath the keep for castle dungeon placement",
      "Mix four stone types for damp aged texture",
      "Split cells to hold many prisoners at once",
      "Redstone dust on floor simulates blood trails",
      "Variation: lava-filled obsidian impenetrable walls",
      "Variation: oubliette obsidian pit with trapdoor ceiling",
      "Variation: basic dirt cobblestone makeshift cells",
      "Variation: torture chamber with stretch rack and iron maiden",
      "Easy build, ~1 hour",
    ),
  ),
  "fortress_village_house": BookBuild(
    id="fortress_village_house",
    name="Village House",
    theme="medieval",
    biome="plains",
    caption=(
      "a medieval tudor village house with cobblestone ground floor, dark oak timber "
      "frame, oak plank upper walls, dark oak gabled roof, second floor balcony, "
      "ground floor kitchen with furnaces and red carpet, bedroom with red bed "
      "and blue rug, gravel garden path and fenced vegetable patch"
    ),
    palette=(
      "minecraft:cobblestone",
      "minecraft:cobblestone_stairs",
      "minecraft:dark_oak_log",
      "minecraft:dark_oak_planks",
      "minecraft:dark_oak_stairs",
      "minecraft:dark_oak_slab",
      "minecraft:dark_oak_fence",
      "minecraft:oak_planks",
      "minecraft:oak_trapdoor",
      "minecraft:oak_door",
      "minecraft:glass_pane",
      "minecraft:spruce_fence",
      "minecraft:red_carpet",
      "minecraft:blue_carpet",
      "minecraft:red_bed",
      "minecraft:furnace",
      "minecraft:smoker",
      "minecraft:chest",
      "minecraft:crafting_table",
      "minecraft:painting",
      "minecraft:torch",
      "minecraft:gravel",
      "minecraft:grass_block",
      "minecraft:poppy",
      "minecraft:oxeye_daisy",
      "minecraft:wheat",
      "minecraft:carrots",
      "minecraft:composter",
    ),
    zones=(
      BuildZone(
        name="ground floor interior",
        size=(8, 4, 6),
        materials=("cobblestone", "oak_planks", "red_carpet"),
        features=("stone foundation kitchen", "red carpet living area"),
        interior=(
          "two furnaces in stone alcove",
          "chest storage",
          "crafting table",
          "paintings on walls",
          "dark oak stairs to upper floor",
        ),
      ),
      BuildZone(
        name="bedroom upper floor",
        size=(9, 5, 7),
        materials=("oak_planks", "dark_oak_log", "blue_carpet"),
        features=("timber frame upper walls", "overhanging second floor"),
        interior=(
          "red bed against wall",
          "blue carpet rug",
          "chest",
          "paintings",
          "spruce fence stair railing",
        ),
      ),
      BuildZone(
        name="exterior and garden",
        size=(12, 8, 10),
        materials=("gravel", "grass_block", "dark_oak_fence", "oak_trapdoor"),
        features=(
          "gravel cobblestone entrance path",
          "flower planters with trapdoors",
          "fenced wheat and carrot garden",
          "composter",
        ),
        interior=("poppies", "oxeye daisies"),
      ),
      BuildZone(
        name="roof and balcony",
        size=(10, 7, 3),
        materials=("dark_oak_stairs", "dark_oak_slab", "dark_oak_fence"),
        features=(
          "steep gabled dark oak roof",
          "roof overhang one block past walls",
          "side balcony with fence railing",
        ),
        interior=(),
      ),
      BuildZone(
        name="inspiration medieval bungalow",
        size=(0, 0, 0),
        materials=(
          "dark_oak_stairs",
          "dark_oak_planks",
          "dark_oak_fence",
          "cobblestone",
          "white_wool",
          "dark_oak_log",
        ),
        features=(
          "single story open plan layout",
          "wide roof overhang covered porch",
          "side pet annex with fence",
          "no interior walls save space",
        ),
        interior=("bed furnace open plan", "pet annex"),
      ),
      BuildZone(
        name="inspiration elevated house",
        size=(0, 0, 0),
        materials=(
          "cobblestone",
          "cobblestone_wall",
          "dark_oak_stairs",
          "dark_oak_planks",
          "lantern",
          "oak_trapdoor",
        ),
        features=(
          "cobblestone base panic room storage",
          "external wooden staircase to second floor",
          "trapdoor window shutters",
          "lantern wall lighting",
        ),
        interior=("ground floor storage panic room", "upper living quarters"),
      ),
      BuildZone(
        name="inspiration rural farmhouse",
        size=(0, 0, 0),
        materials=(
          "dark_oak_planks",
          "diorite",
          "acacia_planks",
          "netherrack",
          "cobweb",
          "oak_sign",
          "item_frame",
          "yellow_wool",
          "wheat",
          "carrots",
        ),
        features=(
          "curved steep A-frame roof",
          "diorite chimney with netherrack fire",
          "cobweb chimney smoke effect",
          "oak sign shelf detailing",
          "fenced crop garden",
        ),
        interior=(
          "yellow carpet hearth room",
          "crafting table",
          "furnace fireplace",
          "item frame wall decor",
          "large skull painting",
        ),
      ),
    ),
    exterior_features=(
      "half-timbered dark oak log frame on oak plank walls",
      "cobblestone stone foundation ground floor",
      "fenestral vertical slit windows without glass",
      "dark oak gabled roof with dormer gable",
      "gravel path to wooden door entrance",
      "torch lighting on exterior logs",
    ),
    tips=(
      "Build many varied village houses around the castle",
      "Stone foundation prevents wooden frame from rotting",
      "Roof overhangs walls by one block using temporary support",
      "Fenestral windows are narrow 1x2 slits without glass",
      "Variation: bungalow open plan with pet annex",
      "Variation: elevated house with cobblestone panic room base",
      "Variation: rural farmhouse curved roof and crop garden",
      "Use paintings signs and item frames for medieval interior decor",
      "Beginner build, ~1 hour",
    ),
  ),
  "fortress_market_square": BookBuild(
    id="fortress_market_square",
    name="Market Square",
    theme="medieval",
    biome="plains",
    caption=(
      "a medieval village market square with central stone well, cobblestone cross "
      "paths, blacksmith stall with blast furnaces, grocer stall with chest storage "
      "and blue white wool canopy, bakery with furnaces and cake, alchemist stall "
      "with brewing stand and cauldron"
    ),
    palette=(
      "minecraft:grass_block",
      "minecraft:gravel",
      "minecraft:cobblestone",
      "minecraft:stone_bricks",
      "minecraft:water",
      "minecraft:dark_oak_log",
      "minecraft:dark_oak_fence",
      "minecraft:dark_oak_planks",
      "minecraft:dark_oak_slab",
      "minecraft:dark_oak_stairs",
      "minecraft:spruce_log",
      "minecraft:spruce_planks",
      "minecraft:spruce_stairs",
      "minecraft:spruce_slab",
      "minecraft:oak_fence",
      "minecraft:oak_planks",
      "minecraft:white_wool",
      "minecraft:orange_wool",
      "minecraft:blue_wool",
      "minecraft:white_carpet",
      "minecraft:black_carpet",
      "minecraft:blast_furnace",
      "minecraft:furnace",
      "minecraft:chest",
      "minecraft:brewing_stand",
      "minecraft:cauldron",
      "minecraft:stonecutter",
      "minecraft:anvil",
      "minecraft:cake",
      "minecraft:torch",
      "minecraft:poppy",
      "minecraft:oxeye_daisy",
      "minecraft:quartz_block",
      "minecraft:quartz_stairs",
      "minecraft:glowstone",
      "minecraft:end_stone_bricks",
      "minecraft:cracked_stone_bricks",
      "minecraft:gold_block",
      "minecraft:rose_bush",
      "minecraft:hay_block",
    ),
    zones=(
      BuildZone(
        name="central well",
        size=(4, 3, 4),
        materials=("stone_bricks", "water", "dark_oak_fence"),
        features=(
          "stone brick well base",
          "water source",
          "dark oak fence corner posts",
          "flowers around well rim",
        ),
        interior=(),
      ),
      BuildZone(
        name="blacksmith stall",
        size=(10, 4, 4),
        materials=("dark_oak_log", "dark_oak_slab", "white_wool", "orange_wool"),
        features=(
          "open front stall",
          "white wool counter",
          "dark oak log pillars",
          "white orange wool roof accent",
        ),
        interior=(
          "two blast furnaces against back wall",
          "double chest behind counter",
          "torch on pillar",
        ),
      ),
      BuildZone(
        name="grocer storage stall",
        size=(10, 5, 4),
        materials=("spruce_log", "spruce_planks", "cobblestone", "blue_wool", "white_wool"),
        features=(
          "blue white checkered wool canopy roof",
          "spruce plank counter with black carpet",
          "cobblestone base walls",
        ),
        interior=(
          "six double chests stacked in two rows",
          "spruce plank storage floor",
          "torches on interior pillars",
        ),
      ),
      BuildZone(
        name="bakery food stall",
        size=(4, 4, 10),
        materials=("dark_oak_fence", "spruce_planks", "white_carpet", "spruce_slab"),
        features=(
          "L-shaped dark oak fence enclosure",
          "white carpet counter",
          "cake on spruce slab display",
        ),
        interior=(
          "three furnaces cooking area",
          "chest storage",
          "torch lighting",
        ),
      ),
      BuildZone(
        name="alchemist stall",
        size=(4, 3, 10),
        materials=("dark_oak_fence", "dark_oak_planks", "dark_oak_fence_gate"),
        features=(
          "fence perimeter open stall",
          "dark oak plank counter",
        ),
        interior=(
          "brewing stand on counter",
          "water cauldron",
          "stonecutter workstation",
          "anvil repair corner",
        ),
      ),
      BuildZone(
        name="square paving",
        size=(16, 1, 16),
        materials=("grass_block", "cobblestone", "gravel"),
        features=(
          "cobblestone gravel cross paths",
          "grass between stalls",
          "poppies and daisies in corners",
          "perimeter torch posts",
        ),
        interior=(),
      ),
      BuildZone(
        name="inspiration fountain plaza",
        size=(0, 0, 0),
        materials=(
          "quartz_block",
          "quartz_stairs",
          "dark_oak_slab",
          "glowstone",
          "oak_fence",
          "white_wool",
          "rose_bush",
        ),
        features=(
          "central quartz tiered fountain",
          "four corner mini fountains",
          "oak fence L-shaped seating stalls",
          "rose bush planters",
        ),
        interior=("chests in seating stalls", "white wool bench counters"),
      ),
      BuildZone(
        name="inspiration livestock trading",
        size=(0, 0, 0),
        materials=(
          "stone_bricks",
          "cobblestone",
          "dark_oak_slab",
          "oak_fence",
          "hay_block",
        ),
        features=(
          "L-shaped open air livestock pen",
          "dark oak slab counters",
          "oak fence animal enclosures",
        ),
        interior=("chest storage on counters", "hay bale feeding troughs"),
      ),
      BuildZone(
        name="inspiration trade quarter",
        size=(0, 0, 0),
        materials=(
          "stone_bricks",
          "dark_oak_log",
          "white_wool",
          "spruce_stairs",
          "glass_pane",
        ),
        features=(
          "timber framed two story shops",
          "stone brick ground floor storefronts",
          "spruce bench seating in plaza",
        ),
        interior=("dark oak slab shop counters", "chest storage behind counters"),
      ),
      BuildZone(
        name="inspiration dockside market",
        size=(0, 0, 0),
        materials=(
          "oak_planks",
          "dark_oak_log",
          "spruce_slab",
          "lantern",
        ),
        features=(
          "T-shaped oak plank jetty",
          "dark oak log dock pilings",
          "tiny spruce slab roof chest stalls",
        ),
        interior=("dock master house bed desk", "chest market stalls on jetty"),
      ),
      BuildZone(
        name="inspiration monuments",
        size=(0, 0, 0),
        materials=(
          "end_stone_bricks",
          "stone_bricks",
          "cracked_stone_bricks",
          "gold_block",
          "quartz_block",
        ),
        features=(
          "hero statue with cobblestone spear",
          "seated merchant golem with gold chest",
          "reclining quartz sphinx",
          "wishing fountain with glowstone",
        ),
        interior=(),
      ),
    ),
    exterior_features=(
      "grass block square with cobblestone gravel cross paths",
      "central stone brick well with water and fence posts",
      "four themed market stalls one block apart",
      "dark oak and spruce log stall pillars",
      "colored wool canopy roofs on stalls",
      "torch lighting on fence posts and pillars",
      "flower clusters between paths and stalls",
    ),
    tips=(
      "Leave one block gap between individual stalls",
      "Use counters slabs and wool to define vendor workspace",
      "Cluster chests behind counters for storage density",
      "Place utility blocks furnaces brewing stands anvils logically behind counters",
      "Variation: quartz fountain plaza with seating stalls",
      "Variation: livestock trading pens with hay bales",
      "Variation: timber framed trade quarter shops",
      "Variation: dockside jetty with chest stalls",
      "Add hero golem or sphinx monuments for plaza character",
      "Intermediate build, ~1 hour",
    ),
  ),
  "fortress_travelers_tavern": BookBuild(
    id="fortress_travelers_tavern",
    name="Travelers' Tavern",
    theme="medieval",
    biome="plains",
    caption=(
      "a medieval travelers tavern with L-shaped cobblestone ground floor, wattle "
      "and daub timber framed upper floor, green carpet bar counter, piston stools, "
      "red bed upstairs, cobblestone chimneys, wooden porch and flower boxes"
    ),
    palette=(
      "minecraft:cobblestone",
      "minecraft:stone_bricks",
      "minecraft:cobblestone_wall",
      "minecraft:diorite",
      "minecraft:spruce_log",
      "minecraft:spruce_planks",
      "minecraft:spruce_stairs",
      "minecraft:dark_oak_stairs",
      "minecraft:dark_oak_log",
      "minecraft:green_terracotta",
      "minecraft:green_carpet",
      "minecraft:oak_planks",
      "minecraft:oak_trapdoor",
      "minecraft:oak_fence",
      "minecraft:oak_door",
      "minecraft:glass_pane",
      "minecraft:piston",
      "minecraft:red_bed",
      "minecraft:chest",
      "minecraft:painting",
      "minecraft:item_frame",
      "minecraft:torch",
      "minecraft:furnace",
      "minecraft:barrel",
      "minecraft:grass_block",
      "minecraft:poppy",
      "minecraft:blue_orchid",
      "minecraft:lantern",
      "minecraft:red_terracotta",
      "minecraft:hay_block",
      "minecraft:cobblestone_wall",
      "minecraft:red_carpet",
      "minecraft:white_carpet",
    ),
    zones=(
      BuildZone(
        name="ground floor tavern",
        size=(11, 4, 8),
        materials=("cobblestone", "diorite", "spruce_planks"),
        features=(
          "L-shaped cobblestone ground floor",
          "wrap around green carpet bar",
          "piston bar stools",
          "dark oak stairs to upper floor",
        ),
        interior=(
          "green carpet bar counter with trapdoor gate",
          "two piston stools at bar",
          "furnace kitchen alcove",
          "barrel storage",
          "torches on diorite walls",
        ),
      ),
      BuildZone(
        name="upper bedroom",
        size=(11, 4, 8),
        materials=("spruce_planks", "diorite", "green_terracotta"),
        features=(
          "wattle and daub timber frame upper walls",
          "second floor overhangs ground floor",
          "dormer windows in roof",
        ),
        interior=(
          "red bed against green clay wall",
          "chest at foot of bed",
          "painting above bed",
          "spruce plank floor",
        ),
      ),
      BuildZone(
        name="exterior porch and garden",
        size=(14, 6, 14),
        materials=("stone_bricks", "oak_planks", "oak_fence", "oak_trapdoor"),
        features=(
          "stone brick cobblestone front walkway",
          "raised oak plank porch",
          "flower boxes with trapdoors and poppies",
          "fenced grassy side yard",
          "painting item frame tavern sign",
        ),
        interior=("poppies", "blue orchids"),
      ),
      BuildZone(
        name="roof and chimneys",
        size=(12, 5, 10),
        materials=("spruce_stairs", "dark_oak_stairs", "cobblestone_wall"),
        features=(
          "multi-gabled spruce dark oak roof",
          "two cobblestone wall chimneys",
          "roof dormer windows",
          "complex intersecting gables",
        ),
        interior=(),
      ),
      BuildZone(
        name="inspiration tavern eatery",
        size=(0, 0, 0),
        materials=(
          "oak_planks",
          "oak_log",
          "oak_stairs",
          "furnace",
          "piston",
          "red_carpet",
          "oak_fence",
          "stone_bricks",
        ),
        features=(
          "row of six furnaces kitchen wall",
          "piston tables with red carpet tablecloths",
          "oak stair chair seating",
          "second floor mezzanine dining overlook",
        ),
        interior=("furnace kitchen row", "mezzanine fence railing"),
      ),
      BuildZone(
        name="inspiration boarding house",
        size=(0, 0, 0),
        materials=(
          "stone_bricks",
          "diorite",
          "oak_log",
          "spruce_stairs",
          "red_bed",
          "white_carpet",
        ),
        features=(
          "four story vertical boarding house",
          "ground floor reception counter",
          "common area red bed corner",
          "third floor white carpet dining hall",
          "attic bedroom under rafters",
        ),
        interior=(
          "reception desk ground floor",
          "red bed common room",
          "white carpet long dining table",
          "attic chest storage",
        ),
      ),
      BuildZone(
        name="inspiration stables",
        size=(0, 0, 0),
        materials=(
          "red_terracotta",
          "dark_oak_log",
          "oak_stairs",
          "cobblestone",
          "hay_block",
          "spruce_trapdoor",
        ),
        features=(
          "red terracotta barn with log frame",
          "open front horse bay",
          "cobblestone fence paddock",
          "hitching post fence outside",
        ),
        interior=("hay bale stacks inside barn", "hay bales in outdoor pen"),
      ),
      BuildZone(
        name="inspiration town tavern complex",
        size=(0, 0, 0),
        materials=(
          "cobblestone",
          "white_wool",
          "dark_oak_log",
          "spruce_planks",
          "lantern",
          "oak_fence",
        ),
        features=(
          "two buildings connected by elevated walkway",
          "covered archway for road traffic below",
          "ground floor open air seating",
          "timber framed white upper floors",
        ),
        interior=(
          "outdoor table bench seating",
          "lanterns under walkway",
          "balcony trapdoor details",
        ),
      ),
    ),
    exterior_features=(
      "L-shaped two story medieval tavern footprint",
      "cobblestone ground floor stone foundation",
      "wattle and daub diorite white walls with dark oak timber frame",
      "second floor overhangs ground floor one block",
      "steep multi-gabled spruce dark oak roof",
      "two cobblestone wall chimneys",
      "oak trapdoor window shutters",
      "torch lighting on exterior stone walls",
      "painting tavern sign for illiterate travelers",
    ),
    tips=(
      "Wattle and daub: white diorite infill between dark oak log grid",
      "Stone ground floor protects wooden frame from moisture",
      "Bar counter uses green carpet on wood with trapdoor gate",
      "Pistons make compact bar stools",
      "Roof overhangs use temporary support block trick",
      "Tavern signs use paintings or item frames with pictures",
      "Variation: tavern eatery with furnace kitchen and mezzanine",
      "Variation: four story boarding house for many travelers",
      "Variation: red terracotta stables with hay bale storage",
      "Variation: twin buildings with elevated walkway archway",
      "Easy build, ~1.5 hours",
    ),
  ),
  "fortress_cathedral": BookBuild(
    id="fortress_cathedral",
    name="Cathedral",
    theme="medieval",
    biome="plains",
    caption=(
      "a medieval stone cathedral with stone brick buttresses, spruce gabled roof, "
      "yellow stained glass rose window, dark oak pew rows, spruce plank central aisle, "
      "white wool altar, iron bar side windows, bell tower with note block bells"
    ),
    palette=(
      "minecraft:stone_bricks",
      "minecraft:chiseled_stone_bricks",
      "minecraft:cracked_stone_bricks",
      "minecraft:cobblestone",
      "minecraft:stone_brick_stairs",
      "minecraft:stone_brick_slab",
      "minecraft:stone_brick_wall",
      "minecraft:spruce_planks",
      "minecraft:spruce_stairs",
      "minecraft:spruce_slab",
      "minecraft:dark_oak_stairs",
      "minecraft:yellow_stained_glass",
      "minecraft:orange_stained_glass",
      "minecraft:blue_stained_glass",
      "minecraft:iron_bars",
      "minecraft:spruce_door",
      "minecraft:white_wool",
      "minecraft:torch",
      "minecraft:lantern",
      "minecraft:ladder",
      "minecraft:note_block",
      "minecraft:redstone_wire",
      "minecraft:redstone_torch",
      "minecraft:repeater",
      "minecraft:grass_block",
      "minecraft:red_terracotta",
      "minecraft:cobblestone_stairs",
    ),
    zones=(
      BuildZone(
        name="nave interior",
        size=(12, 6, 15),
        materials=("stone_bricks", "spruce_planks", "dark_oak_stairs"),
        features=(
          "long rectangular nave hall",
          "spruce plank central aisle",
          "stone brick pillar colonnade",
        ),
        interior=(
          "eight rows dark oak stair pews each side",
          "white wool altar at far end",
          "torch lanterns on stone pillars",
          "spruce plank center aisle path",
        ),
      ),
      BuildZone(
        name="facade and entrance",
        size=(12, 9, 3),
        materials=("stone_bricks", "yellow_stained_glass", "spruce_door"),
        features=(
          "gabled stone brick entrance porch",
          "2x2 yellow stained glass rose window",
          "stone brick arch doorway",
        ),
        interior=(),
      ),
      BuildZone(
        name="walls and buttresses",
        size=(14, 8, 16),
        materials=("stone_bricks", "cracked_stone_bricks", "cobblestone"),
        features=(
          "stone brick nave walls with cracked texture mix",
          "exterior buttress pillars every four blocks",
          "iron bar slit side windows",
          "stone brick wall roof finials",
        ),
        interior=(),
      ),
      BuildZone(
        name="roof",
        size=(12, 5, 15),
        materials=("spruce_stairs", "spruce_planks", "stone_brick_stairs"),
        features=(
          "steep A-frame spruce stair roof",
          "stone brick stair roof edge trim",
          "lower shed roofs over side aisles",
          "decorative stone wall cross finials",
        ),
        interior=(),
      ),
      BuildZone(
        name="bell tower",
        size=(4, 10, 4),
        materials=("stone_bricks", "spruce_planks", "ladder"),
        features=(
          "square stone bell tower at entrance",
          "crenellated battlement crown",
          "multi-level wooden platforms",
        ),
        interior=(
          "ladder access between floors",
          "note block bell system on top platform",
          "redstone repeater timing circuit",
          "torches on interior walls",
        ),
      ),
      BuildZone(
        name="apse stained glass",
        size=(8, 6, 2),
        materials=("yellow_stained_glass", "orange_stained_glass"),
        features=(
          "large yellow orange diamond stained glass window",
          "back apse wall window",
        ),
        interior=(),
      ),
      BuildZone(
        name="inspiration gothic cathedral",
        size=(0, 0, 0),
        materials=(
          "chiseled_stone_bricks",
          "cracked_stone_bricks",
          "cobblestone_wall",
          "blue_stained_glass",
          "cyan_stained_glass",
          "lantern",
        ),
        features=(
          "tall pointed arch stained glass window",
          "blue cyan yellow glass cross pattern",
          "cobblestone wall buttress supports",
          "small side chapel with lantern",
        ),
        interior=("lantern lit side chapel",),
      ),
      BuildZone(
        name="inspiration rustic stave church",
        size=(0, 0, 0),
        materials=(
          "red_terracotta",
          "dark_oak_log",
          "spruce_stairs",
          "cobblestone_stairs",
        ),
        features=(
          "red terracotta lower walls",
          "cobblestone stair roof edge trim",
          "four tier overlapping steep roofs",
          "log corner pillar supports",
        ),
        interior=("dense wooden pillar forest nave",),
      ),
      BuildZone(
        name="inspiration stained glass patterns",
        size=(0, 0, 0),
        materials=(
          "yellow_stained_glass",
          "lime_stained_glass",
          "blue_stained_glass",
          "white_stained_glass",
          "red_stained_glass",
        ),
        features=(
          "flower medallion circular glass pattern",
          "checkerboard red white glass grid",
          "stone brick stair window frame",
        ),
        interior=(),
      ),
    ),
    exterior_features=(
      "long stone brick cathedral nave with side aisles",
      "exterior buttresses support heavy spruce roof",
      "yellow stained glass rose window above entrance",
      "iron bar medieval side windows",
      "steep spruce gabled roof with stone trim",
      "stone brick wall cross finials on roof peaks",
      "bell tower with crenellated battlements",
      "grass foundation with small pond and flowers",
    ),
    tips=(
      "Start with floor layout before walls and roof",
      "Buttresses project outward to support roof weight",
      "Mix stone brick cracked and chiseled for wall texture",
      "Stained glass windows told stories to illiterate villagers",
      "Dark oak stairs make compact pew seating rows",
      "Bell tower uses note blocks with redstone repeater timing",
      "Variation: Gothic cathedral with blue stained glass arch",
      "Variation: rustic red terracotta stave church tiered roofs",
      "Variation: flower or checkerboard stained glass patterns",
      "Intermediate build, ~2 hours",
    ),
  ),
  "fortress_castle_bits": BookBuild(
    id="fortress_castle_bits",
    name="Castle Finishing Touches",
    theme="medieval",
    biome="plains",
    caption=(
      "medieval castle finishing touches with beacon tower, checkered flag pole, "
      "notice board, hay carts, storage hold, signpost, guard post lookout, "
      "and cobblestone village well"
    ),
    palette=(
      "minecraft:grass_block",
      "minecraft:cobblestone",
      "minecraft:stone_bricks",
      "minecraft:stone_brick_stairs",
      "minecraft:stone_brick_slab",
      "minecraft:chiseled_stone_bricks",
      "minecraft:cobblestone_wall",
      "minecraft:dark_oak_planks",
      "minecraft:dark_oak_stairs",
      "minecraft:dark_oak_slab",
      "minecraft:spruce_planks",
      "minecraft:spruce_fence",
      "minecraft:spruce_trapdoor",
      "minecraft:spruce_slab",
      "minecraft:oak_planks",
      "minecraft:oak_fence",
      "minecraft:oak_fence_gate",
      "minecraft:oak_sign",
      "minecraft:oak_trapdoor",
      "minecraft:oak_slab",
      "minecraft:ladder",
      "minecraft:netherrack",
      "minecraft:torch",
      "minecraft:red_wool",
      "minecraft:white_wool",
      "minecraft:hay_block",
      "minecraft:barrel",
      "minecraft:oak_log",
      "minecraft:water",
      "minecraft:short_grass",
      "minecraft:stone_button",
    ),
    zones=(
      BuildZone(
        name="beacon tower",
        size=(3, 12, 3),
        materials=("cobblestone", "stone_bricks", "dark_oak_stairs", "netherrack"),
        features=(
          "stone cobblestone pillar tower",
          "dark oak wood decorative band",
          "netherrack fire brazier top",
          "dark oak stair roof with torches",
        ),
        interior=("netherrack eternal flame", "torch corner lighting"),
      ),
      BuildZone(
        name="flag pole",
        size=(4, 14, 4),
        materials=("cobblestone", "spruce_fence", "red_wool", "white_wool"),
        features=(
          "tall spruce fence flagpole",
          "red white checkered waving wool flag",
          "ladder on pole side",
          "torch and slab topper",
        ),
        interior=(),
      ),
      BuildZone(
        name="notice board",
        size=(3, 5, 3),
        materials=("stone_brick_slab", "cobblestone_wall", "oak_trapdoor", "oak_slab"),
        features=(
          "stone slab base platform",
          "cobblestone wall corner pillars",
          "trapdoor sign boards on center post",
          "tiered oak slab roof with torches",
        ),
        interior=("short grass under board", "spruce trapdoor announcement panels"),
      ),
      BuildZone(
        name="hay carts",
        size=(6, 3, 4),
        materials=("spruce_slab", "spruce_trapdoor", "hay_block", "oak_fence"),
        features=(
          "spruce slab wagon chassis",
          "trapdoor side walls",
          "hay bale cargo load",
          "oak fence horse hitch",
        ),
        interior=("hay bale stacked cargo", "empty open wagon variant"),
      ),
      BuildZone(
        name="storage hold",
        size=(5, 4, 3),
        materials=("cobblestone", "oak_fence_gate", "stone_brick_slab", "oak_fence"),
        features=(
          "cobblestone platform base",
          "oak fence gate front",
          "stone brick slab roof on fence posts",
        ),
        interior=("oak log supply stacks", "barrel storage behind gates"),
      ),
      BuildZone(
        name="signpost",
        size=(3, 4, 1),
        materials=("stone_brick_slab", "chiseled_stone_bricks", "cobblestone_wall", "oak_sign"),
        features=(
          "stone brick slab ground line",
          "chiseled stone brick pillar",
          "oak signs both directions",
          "torches on cobblestone wall cap",
        ),
        interior=(),
      ),
      BuildZone(
        name="guard post",
        size=(3, 5, 3),
        materials=("cobblestone", "spruce_planks", "stone_brick_stairs", "spruce_fence"),
        features=(
          "raised cobblestone base platform",
          "spruce plank lookout floor",
          "stone brick stair lean-to roof",
          "spruce fence post supports",
        ),
        interior=("torch lighting on platform corners",),
      ),
      BuildZone(
        name="village well",
        size=(4, 5, 4),
        materials=("cobblestone", "water", "oak_fence", "torch"),
        features=(
          "cobblestone rim 4x4 water well",
          "oak fence corner pillars",
          "fence trellis frame over water",
          "torches on pillar tops",
        ),
        interior=("water source blocks in well basin",),
      ),
    ),
    exterior_features=(
      "collection of small medieval castle village props",
      "grass courtyard display pad",
      "beacon lighthouse signal fire tower",
      "territory marking checkered flag",
      "announcement notice board and signpost",
      "supply carts and storage hold",
      "elevated guard lookout post",
      "central village well with trellis",
    ),
    tips=(
      "Scatter props around castle walls and village paths",
      "Beacons use netherrack for permanent fire",
      "Flags mark kingdom territory with colored wool",
      "Notice boards use trapdoors and signs as panels",
      "Carts use slabs trapdoors and hay bales for cargo wagons",
      "Storage holds keep barrels and logs behind fence gates",
      "Guard posts give elevated sentry vantage points",
      "Wells need fence trellis and torches for night lighting",
      "Quick builds, ~15 minutes each",
    ),
  ),
  "fortress_lava_trap": BookBuild(
    id="fortress_lava_trap",
    name="Lava Trap Room",
    theme="medieval",
    biome="plains",
    caption=(
      "a castle lava trap room with stone brick walls, trapped chest bait, "
      "ceiling dispenser lava release, sticky piston door seal, redstone "
      "repeater circuit, yellow wool wiring paths"
    ),
    palette=(
      "minecraft:stone_bricks",
      "minecraft:cobblestone",
      "minecraft:chiseled_stone_bricks",
      "minecraft:stone_brick_stairs",
      "minecraft:dispenser",
      "minecraft:sticky_piston",
      "minecraft:piston",
      "minecraft:redstone_wire",
      "minecraft:redstone_torch",
      "minecraft:repeater",
      "minecraft:trapped_chest",
      "minecraft:lava",
      "minecraft:yellow_wool",
      "minecraft:iron_bars",
      "minecraft:lever",
    ),
    zones=(
      BuildZone(
        name="trap chamber",
        size=(7, 4, 7),
        materials=("stone_bricks", "cobblestone", "lava"),
        features=(
          "stone brick enclosed trap room",
          "cobblestone floor base",
          "lava column from ceiling",
          "no escape once triggered",
        ),
        interior=(
          "trapped chest loot bait in center alcove",
          "lava pool filling chamber floor",
          "iron bars lava flow guides",
        ),
      ),
      BuildZone(
        name="ceiling lava release",
        size=(5, 2, 5),
        materials=("dispenser", "sticky_piston", "lava", "yellow_wool"),
        features=(
          "3x3 dispenser grid facing down",
          "lava reservoir trough above ceiling",
          "sticky pistons hold lava until triggered",
        ),
        interior=("lava buckets in dispensers",),
      ),
      BuildZone(
        name="piston door seal",
        size=(3, 4, 2),
        materials=("sticky_piston", "stone_bricks", "piston"),
        features=(
          "vertical sticky piston door column",
          "three pistons seal entrance on trigger",
          "parallel circuit with lava release",
        ),
        interior=(),
      ),
      BuildZone(
        name="redstone circuit",
        size=(9, 6, 9),
        materials=("redstone_wire", "redstone_torch", "repeater", "yellow_wool"),
        features=(
          "trapped chest triggers repeater signal",
          "vertical redstone torch ladder on yellow blocks",
          "parallel circuits for door and lava",
          "exterior ledge redstone wiring",
        ),
        interior=(
          "repeater behind trapped chest",
          "redstone dust on yellow wool paths",
          "redstone torch vertical signal ladder",
        ),
      ),
    ),
    exterior_features=(
      "compact 9x9 stone brick castle trap room",
      "hidden redstone wiring on exterior walls",
      "yellow wool highlights redstone signal paths",
      "lever test trigger on outside",
      "tiered stone brick stair wall trim",
      "thermal weapon medieval castle defense",
    ),
    tips=(
      "Trapped chest bait draws enemies into trap chamber",
      "Parallel redstone triggers lava and door simultaneously",
      "Activate pistons before pouring lava into reservoir",
      "Test trapped chest opens and closes mechanism first",
      "Avoid flammable blocks near lava reservoir",
      "Use yellow wool to trace redstone wiring paths",
      "Vertical torch ladder carries signal floor to ceiling",
      "Dispensers release lava from ceiling grid",
      "Easy build, ~2 hours",
    ),
  ),
  "fortress_hidden_pitfall": BookBuild(
    id="fortress_hidden_pitfall",
    name="Hidden Pitfall",
    theme="medieval",
    biome="plains",
    caption=(
      "a castle hidden pitfall trap with stone brick hallway, tripwire trigger, "
      "2x2 sticky piston floor drop, sequenced vertical and horizontal pistons, "
      "redstone repeater delay circuit, painting and torch furnished chamber"
    ),
    palette=(
      "minecraft:stone_bricks",
      "minecraft:cobblestone",
      "minecraft:spruce_door",
      "minecraft:sticky_piston",
      "minecraft:piston",
      "minecraft:redstone_wire",
      "minecraft:redstone_torch",
      "minecraft:repeater",
      "minecraft:yellow_wool",
      "minecraft:tripwire_hook",
      "minecraft:string",
      "minecraft:painting",
      "minecraft:torch",
      "minecraft:cactus",
      "minecraft:lever",
    ),
    zones=(
      BuildZone(
        name="trap hallway chamber",
        size=(9, 4, 7),
        materials=("stone_bricks", "spruce_door", "painting", "torch"),
        features=(
          "stone brick dungeon hallway room",
          "spruce door entrance",
          "tripwire string across narrow passage",
          "painting wall decoration",
        ),
        interior=(
          "torches flanking doorway",
          "painting on side wall",
          "2x2 hidden floor trap in center",
        ),
      ),
      BuildZone(
        name="piston floor mechanism",
        size=(4, 3, 4),
        materials=("sticky_piston", "stone_bricks", "piston"),
        features=(
          "2x2 sticky piston floor blocks",
          "vertical pistons drop floor first",
          "horizontal pistons pull floor blocks aside",
          "sequenced piston retraction",
        ),
        interior=(),
      ),
      BuildZone(
        name="redstone delay circuit",
        size=(10, 2, 8),
        materials=("redstone_wire", "repeater", "redstone_torch", "yellow_wool"),
        features=(
          "yellow wool redstone wiring base",
          "repeater ticks 1 3 and 4 delay sequence",
          "front back circuit split with torch inverter",
          "tripwire powers torch off to open floor",
        ),
        interior=(
          "redstone torch faces front piston section",
          "repeater delay chains for piston sequence",
          "perimeter redstone dust loop",
        ),
      ),
      BuildZone(
        name="pit below",
        size=(4, 6, 4),
        materials=("cactus", "cobblestone"),
        features=(
          "deep pit below trap floor",
          "cactus damage at pit bottom",
          "trou de loup wolf hole medieval trap",
        ),
        interior=("cactus spikes at pit bottom",),
      ),
    ),
    exterior_features=(
      "compact stone brick castle hallway trap",
      "concealed 3 deep 10 wide 8 long mechanism pit",
      "tripwire hook wall recess with string line",
      "block gap between hook wall and redstone layer",
      "floor resets after intruder falls",
    ),
    tips=(
      "Tripwire triggers back circuit turning off front torch",
      "Front circuit powers pistons extended by default",
      "Vertical pistons drop floor then horizontal pull aside",
      "Use repeaters at 1 3 and 4 tick delays for sequence",
      "Leave block gap under tripwire hook for redstone",
      "Build mechanism in ditch under hall floor",
      "Fill pit bottom with lava or cacti for damage",
      "Leave one block gap in wall for tripwire string",
      "Easy build, ~1.5 hours",
    ),
  ),
  "fortress_arrow_gauntlet": BookBuild(
    id="fortress_arrow_gauntlet",
    name="Arrow Gauntlet",
    theme="medieval",
    biome="plains",
    caption=(
      "a castle arrow gauntlet hallway trap with stone brick walls, dark oak "
      "trim, wall dispensers firing arrows, stone pressure plate floor grid, "
      "redstone pulse clock circuit, double doors and torches at far end"
    ),
    palette=(
      "minecraft:stone_bricks",
      "minecraft:chiseled_stone_bricks",
      "minecraft:cobblestone",
      "minecraft:dark_oak_log",
      "minecraft:dark_oak_planks",
      "minecraft:spruce_planks",
      "minecraft:spruce_stairs",
      "minecraft:dispenser",
      "minecraft:stone_pressure_plate",
      "minecraft:redstone_wire",
      "minecraft:redstone_torch",
      "minecraft:repeater",
      "minecraft:yellow_wool",
      "minecraft:dark_oak_door",
      "minecraft:torch",
      "minecraft:arrow",
    ),
    zones=(
      BuildZone(
        name="gauntlet hallway",
        size=(8, 5, 14),
        materials=("stone_bricks", "dark_oak_log", "dark_oak_planks"),
        features=(
          "stone brick murder hole hallway",
          "dark oak log ceiling and base trim",
          "spruce plank entrance walkway",
          "double dark oak doors at far end",
        ),
        interior=(
          "stone pressure plates covering entire floor",
          "torches flanking exit doors",
          "staggered wall dispensers both sides",
        ),
      ),
      BuildZone(
        name="dispenser walls",
        size=(2, 2, 14),
        materials=("dispenser", "chiseled_stone_bricks"),
        features=(
          "four dispensers per side at head height",
          "staggered offset pattern avoids crossfire",
          "dispensers filled with arrows",
          "every hallway block in arrow range",
        ),
        interior=("arrow filled dispensers",),
      ),
      BuildZone(
        name="redstone pulse grid",
        size=(8, 2, 14),
        materials=("redstone_wire", "repeater", "redstone_torch", "yellow_wool"),
        features=(
          "yellow wool under-floor redstone grid",
          "pressure plate per redstone block below",
          "rapid pulse clock for continuous firing",
          "one tick repeaters to dispensers",
        ),
        interior=(
          "redstone torch pulse clock mechanism",
          "repeater signal boost every 15 blocks",
          "perimeter redstone dust grid",
        ),
      ),
    ),
    exterior_features=(
      "10 wide 12 long stone brick castle hallway trap",
      "murder hole gatehouse defense corridor",
      "hidden redstone wiring behind dispenser walls",
      "spruce stair wall trim accents",
      "continuous arrow hail when plates triggered",
    ),
    tips=(
      "Cover entire floor with pressure plates for no safe steps",
      "Place redstone block under every pressure plate",
      "Stagger dispensers so arrows cover all floor tiles",
      "Pulse clock makes dispensers fire repeatedly not once",
      "Set repeaters to one tick for rapid fire",
      "Add repeaters every 15 blocks for long hallways",
      "Use stone plates hidden on stone brick floor",
      "Best placed in castle gatehouse after outer gates",
      "Experienced build, ~2 hours",
    ),
  ),
  "fortress_arrow_catapult": BookBuild(
    id="fortress_arrow_catapult",
    name="Arrow Catapult",
    theme="medieval",
    biome="plains",
    caption=(
      "a castle arrow catapult siege defense with yellow wool launch platform, "
      "slime block sticky piston catapult, TNT dispensers, elevated arrow "
      "reloading walkway, redstone comparator clock, tripwire automation"
    ),
    palette=(
      "minecraft:grass_block",
      "minecraft:yellow_wool",
      "minecraft:dispenser",
      "minecraft:sticky_piston",
      "minecraft:slime_block",
      "minecraft:tnt",
      "minecraft:redstone_wire",
      "minecraft:redstone_torch",
      "minecraft:redstone_block",
      "minecraft:repeater",
      "minecraft:comparator",
      "minecraft:oak_fence",
      "minecraft:dark_oak_fence",
      "minecraft:ladder",
      "minecraft:stone_button",
      "minecraft:tripwire_hook",
      "minecraft:string",
      "minecraft:dark_oak_planks",
    ),
    zones=(
      BuildZone(
        name="launch platform",
        size=(7, 3, 7),
        materials=("yellow_wool", "sticky_piston", "slime_block", "dispenser"),
        features=(
          "5x5 yellow wool elevated platform on fence posts",
          "2x2 sticky pistons with 3x3 slime block pad",
          "six upward dispensers around perimeter",
          "TNT dispensers above launch point",
        ),
        interior=(
          "slime blocks on sticky piston catapult arms",
          "TNT dispensed onto slime before piston launch",
          "arrow dispensers around platform edge",
        ),
      ),
      BuildZone(
        name="reloading walkway",
        size=(7, 10, 3),
        materials=("dark_oak_planks", "dark_oak_fence", "ladder", "dispenser"),
        features=(
          "high wooden walkway sixteen blocks above launchers scaled",
          "T-shaped cross platform with arrow dispensers",
          "four downward dispensers over slime pad",
          "ladder access from ground",
        ),
        interior=(
          "arrow filled dispensers on cross arms",
          "comparator redstone block rapid fire clock",
        ),
      ),
      BuildZone(
        name="timing circuit",
        size=(12, 2, 5),
        materials=("yellow_wool", "repeater", "redstone_wire", "stone_button"),
        features=(
          "button activated 4 tick repeater delay line",
          "delayed signal to TNT then piston launch",
          "automated redstone replaces manual button",
        ),
        interior=(
          "seven repeaters at four tick delay",
          "breaker circuit sticky piston redstone block",
        ),
      ),
      BuildZone(
        name="tripwire automation",
        size=(20, 1, 3),
        materials=("tripwire_hook", "string", "redstone_wire"),
        features=(
          "reload tripwire at 170 blocks scaled",
          "fire tripwire at 110 blocks scaled",
          "arrows hit targets at 75 block range",
          "vertical redstone torch tower link",
        ),
        interior=(),
      ),
    ),
    exterior_features=(
      "castle siege arrow catapult long range defense",
      "grass field placement outside castle walls",
      "fence post supported yellow launch platform",
      "elevated operator walkway with ladder",
      "TNT blast propels arrow volley skyward",
    ),
    tips=(
      "Reload platform must be 16 blocks above launchers",
      "TNT dispensed before pistons fire with repeater delay",
      "Slime blocks launch arrows into TNT blast path",
      "Comparator subtraction mode rapid fires arrow dispensers",
      "Place reload tripwire further than fire tripwire",
      "Breaker circuit limits arrows per volley",
      "Use vertical redstone torch tower for ground link",
      "Automate by replacing button with tripwire signal",
      "Experienced build, ~3 hours",
    ),
  ),
  "fortress_dungeon_oubliette": BookBuild(
    id="fortress_dungeon_oubliette",
    name="Oubliette Pit",
    theme="medieval",
    biome="plains",
    caption=(
      "a castle oubliette isolation pit with obsidian walls, ceiling oak trapdoor "
      "entrance, lever controlled drop hatch, iron bar observation window and torch"
    ),
    palette=(
      "minecraft:obsidian",
      "minecraft:stone_bricks",
      "minecraft:oak_planks",
      "minecraft:iron_bars",
      "minecraft:oak_trapdoor",
      "minecraft:lever",
      "minecraft:torch",
    ),
    zones=(
      BuildZone(
        name="obsidian pit",
        size=(4, 6, 4),
        materials=("obsidian", "stone_bricks"),
        features=("deep isolation cell", "obsidian inner shell", "stone brick rim"),
        interior=(),
      ),
      BuildZone(
        name="ceiling hatch",
        size=(2, 1, 2),
        materials=("oak_trapdoor", "lever", "oak_planks"),
        features=("trapdoor floor entrance", "lever controlled hatch"),
        interior=(),
      ),
    ),
    exterior_features=(
      "underground beneath castle keep",
      "iron bar slit observation window",
      "torch on stone brick landing above pit",
    ),
    tips=(
      "Variation from fortress dungeon oubliette spread",
      "Prisoners dropped through ceiling trapdoor",
      "Obsidian prevents easy escape",
    ),
  ),
  "fortress_barracks_forge": BookBuild(
    id="fortress_barracks_forge",
    name="Castle Forge",
    theme="medieval",
    biome="plains",
    caption=(
      "a medieval castle blacksmith forge with open-sided stone brick workshop, "
      "netherrack hearth chimney, anvil repair station, furnace and crafting table"
    ),
    palette=(
      "minecraft:stone_bricks",
      "minecraft:dark_oak_stairs",
      "minecraft:netherrack",
      "minecraft:fire",
      "minecraft:anvil",
      "minecraft:furnace",
      "minecraft:crafting_table",
      "minecraft:chest",
      "minecraft:torch",
    ),
    zones=(
      BuildZone(
        name="forge workshop",
        size=(6, 4, 5),
        materials=("stone_bricks", "dark_oak_stairs"),
        features=("open front blacksmith bay", "stone chimney stack"),
        interior=("anvil", "furnace", "crafting table", "chest"),
      ),
      BuildZone(
        name="hearth chimney",
        size=(2, 5, 2),
        materials=("netherrack", "fire", "stone_bricks"),
        features=("netherrack eternal flame", "stone brick chimney column"),
        interior=("flaming hearth",),
      ),
    ),
    exterior_features=(
      "attached to castle barracks in bailey ward",
      "torch-lit stone brick walls",
      "weapon and armor crafting area",
    ),
    tips=("Variation from fortress barracks forge spread",),
  ),
  "fortress_enchanting_hidden_library": BookBuild(
    id="fortress_enchanting_hidden_library",
    name="Hidden Enchanting Library",
    theme="medieval",
    biome="plains",
    caption=(
      "a hidden castle enchanting library with levitating bookshelf ring on sticky "
      "pistons, stone pressure plate trigger, redstone floor lattice, enchanting "
      "table at center"
    ),
    palette=(
      "minecraft:oak_planks",
      "minecraft:oak_slab",
      "minecraft:bookshelf",
      "minecraft:sticky_piston",
      "minecraft:redstone_dust",
      "minecraft:stone_pressure_plate",
      "minecraft:enchanting_table",
      "minecraft:torch",
    ),
    zones=(
      BuildZone(
        name="enchantment floor",
        size=(7, 1, 7),
        materials=("oak_planks", "redstone_dust", "stone_pressure_plate"),
        features=("7x7 oak floor", "redstone lattice under planks"),
        interior=("enchanting table",),
      ),
      BuildZone(
        name="retractable bookshelves",
        size=(5, 3, 5),
        materials=("bookshelf", "sticky_piston", "oak_slab"),
        features=("U-shaped bookshelf ring", "sticky pistons raise shelves"),
        interior=("15 bookshelves for level 30",),
      ),
    ),
    exterior_features=(
      "concealed room in castle keep",
      "bookshelves retract when plate triggered",
    ),
    tips=("Variation from fortress enchanting hidden library spread",),
  ),
  "fortress_cathedral_bell_tower": BookBuild(
    id="fortress_cathedral_bell_tower",
    name="Cathedral Bell Tower",
    theme="medieval",
    biome="plains",
    caption=(
      "a medieval cathedral bell tower with stone brick shaft, crenellated battlement "
      "crown, spruce plank platforms, ladder access, note block bells and redstone "
      "repeater chime circuit"
    ),
    palette=(
      "minecraft:stone_bricks",
      "minecraft:spruce_planks",
      "minecraft:ladder",
      "minecraft:note_block",
      "minecraft:redstone_wire",
      "minecraft:redstone_torch",
      "minecraft:repeater",
      "minecraft:torch",
    ),
    zones=(
      BuildZone(
        name="bell tower shaft",
        size=(4, 10, 4),
        materials=("stone_bricks", "spruce_planks", "ladder"),
        features=("square stone tower", "multi-level wooden platforms"),
        interior=("ladder between floors",),
      ),
      BuildZone(
        name="bell platform",
        size=(4, 2, 4),
        materials=("note_block", "redstone_wire", "repeater", "torch"),
        features=("note block bell array", "redstone repeater timing circuit"),
        interior=("chime bells on top platform",),
      ),
      BuildZone(
        name="battlement crown",
        size=(4, 2, 4),
        materials=("stone_bricks",),
        features=("crenellated parapet", "corner merlons"),
        interior=(),
      ),
    ),
    exterior_features=(
      "attached to cathedral entrance facade",
      "torch-lit interior walls",
      "crenellated stone crown",
    ),
    tips=("Detail module from fortress cathedral bell tower spread",),
  ),
}
